//! Generates the `PAGES` table consumed by `routes/docs/mod.rs` at
//! build time from `docs/xvnwiki/index.toml`.
//!
//! Layout enforced by this build script:
//!
//! ```text
//! <workspace root>/
//!   docs/xvnwiki/
//!     index.toml          ← ordered [[page]] entries (slug/title/path)
//!     <slug>.md           ← one file per entry
//! ```
//!
//! The generated file is written to `$OUT_DIR/docs_pages.rs` and
//! `include!`'d from `routes/docs/mod.rs`. Every page body is embedded
//! via `include_str!` so the binary carries the content — no runtime
//! filesystem read at startup.
//!
//! Re-run triggers: `index.toml` change, any wiki `.md` change, or the
//! build script itself changing. The wiki directory is otherwise opaque
//! to cargo's change detection so we explicitly emit a `rerun-if-changed`
//! line for each path enumerated in the manifest.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    page: Vec<Page>,
}

#[derive(Deserialize)]
struct Page {
    slug: String,
    title: String,
    path: String,
}

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let wiki_dir = crate_dir
        .join("../../docs/xvnwiki")
        .canonicalize()
        .expect("docs/xvnwiki must exist at workspace root");

    let manifest_path = wiki_dir.join("index.toml");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_src =
        fs::read_to_string(&manifest_path).expect("read docs/xvnwiki/index.toml");
    let manifest: Manifest =
        toml::from_str(&manifest_src).expect("parse docs/xvnwiki/index.toml");

    if manifest.page.is_empty() {
        panic!("docs/xvnwiki/index.toml must list at least one page");
    }

    let mut rows = String::new();
    for page in &manifest.page {
        let md_path = wiki_dir.join(&page.path);
        if !md_path.is_file() {
            panic!(
                "docs/xvnwiki/index.toml references {} but {} is not a file",
                page.path,
                md_path.display()
            );
        }
        // Force cargo to rebuild when any referenced markdown changes.
        println!("cargo:rerun-if-changed={}", md_path.display());

        rows.push_str(&format!(
            "    ({slug:?}, {title:?}, include_str!({path:?})),\n",
            slug = page.slug,
            title = page.title,
            path = md_path.to_string_lossy().into_owned(),
        ));
    }

    let generated = format!(
        "// @generated by build.rs from docs/xvnwiki/index.toml — do not edit.\n\
         pub(super) const PAGES: &[(&str, &str, &str)] = &[\n{rows}];\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("docs_pages.rs");
    fs::write(&out_path, generated).expect("write docs_pages.rs");
}
