//! Generates the `PAGES` table consumed by `routes/docs/mod.rs` at
//! build time from `wiki/index.toml`.
//!
//! Layout enforced by this build script:
//!
//! ```text
//! crates/xvision-dashboard/
//!   wiki/
//!     index.toml          ← ordered [[page]] entries (slug/title/path)
//!     <slug>.md           ← one file per entry
//! ```
//!
//! The wiki lives inside the dashboard crate (not under `docs/`) because
//! `docs/` is gitignored as a dev-only scratch area and also excluded
//! from the Docker build context via `.dockerignore`. Co-locating with
//! the build script that bakes it keeps deploys honest.
//!
//! The generated file is written to `$OUT_DIR/docs_pages.rs` and
//! `include!`'d from `routes/docs/mod.rs`. Every page body is embedded
//! via `include_str!` so the binary carries the content — no runtime
//! filesystem read at startup.
//!
//! Re-run triggers: `index.toml` change, any wiki `.md` change, or the
//! build script itself changing. The wiki directory is otherwise opaque
//! to cargo's change detection so we explicitly emit a `rerun-if-changed`
//! line for each path enumerated in the manifest.

use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    page: Vec<Page>,
}

#[derive(Deserialize)]
struct Page {
    slug: String,
    title: String,
    section: String,
    /// ISO-8601 calendar date (`YYYY-MM-DD`) of the last review pass.
    /// Enforced fresh at runtime by the `pages_reviewed_within_window`
    /// test in `routes/docs/mod.rs`.
    last_reviewed: String,
    path: String,
}

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let wiki_dir = crate_dir
        .join("wiki")
        .canonicalize()
        .expect("crates/xvision-dashboard/wiki must exist");

    let manifest_path = wiki_dir.join("index.toml");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_src = fs::read_to_string(&manifest_path).expect("read wiki/index.toml");
    let manifest: Manifest = toml::from_str(&manifest_src).expect("parse wiki/index.toml");

    if manifest.page.is_empty() {
        panic!("wiki/index.toml must list at least one page");
    }

    let mut rows = String::new();
    let mut review_rows = String::new();
    for page in &manifest.page {
        let md_path = wiki_dir.join(&page.path);
        if !md_path.is_file() {
            panic!(
                "wiki/index.toml references {} but {} is not a file",
                page.path,
                md_path.display()
            );
        }
        validate_iso_date(&page.last_reviewed, &page.slug);
        // Force cargo to rebuild when any referenced markdown changes.
        println!("cargo:rerun-if-changed={}", md_path.display());

        rows.push_str(&format!(
            "    ({slug:?}, {title:?}, {section:?}, include_str!({path:?})),\n",
            slug = page.slug,
            title = page.title,
            section = page.section,
            path = md_path.to_string_lossy().into_owned(),
        ));
        review_rows.push_str(&format!(
            "    ({slug:?}, {last:?}),\n",
            slug = page.slug,
            last = page.last_reviewed,
        ));
    }

    let generated = format!(
        "// @generated by build.rs from wiki/index.toml — do not edit.\n\
         pub(super) const PAGES: &[(&str, &str, &str, &str)] = &[\n{rows}];\n\
         \n\
         /// `(slug, last_reviewed)` for every page. Dates are ISO-8601\n\
         /// (`YYYY-MM-DD`) and are validated in `build.rs`.\n\
         pub(super) const LAST_REVIEWED: &[(&str, &str)] = &[\n{review_rows}];\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("docs_pages.rs");
    fs::write(&out_path, generated).expect("write docs_pages.rs");
}

/// Cheap calendar-date validator: rejects anything that isn't
/// `YYYY-MM-DD` with plausible month/day ranges. Runs at build time so
/// a malformed manifest fails fast instead of producing a `LAST_REVIEWED`
/// table the runtime test can't parse.
fn validate_iso_date(raw: &str, slug: &str) {
    let bytes = raw.as_bytes();
    let ok = bytes.len() == 10
        && bytes[4] == b'-'
        && bytes[7] == b'-'
        && bytes[..4].iter().all(|b| b.is_ascii_digit())
        && bytes[5..7].iter().all(|b| b.is_ascii_digit())
        && bytes[8..].iter().all(|b| b.is_ascii_digit());
    if !ok {
        panic!(
            "wiki/index.toml: `{slug}` has invalid last_reviewed \
             `{raw}` — expected YYYY-MM-DD",
        );
    }
    let month: u32 = raw[5..7].parse().unwrap();
    let day: u32 = raw[8..10].parse().unwrap();
    if !(1..=12).contains(&month) || !(1..=31).contains(&day) {
        panic!(
            "wiki/index.toml: `{slug}` has out-of-range \
             last_reviewed `{raw}`",
        );
    }
}
