// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transition } from "./Transition";

/**
 * Decision the runtime returns for a bar.
 */
export type ActivationDecision = { "kind": "warming", bars_left: number, } | { "kind": "inactive" } | { "kind": "active", transition: Transition, } | { "kind": "cooldown", bars_left: number, } | { "kind": "capped_for_day", wakeups_today: number, } | { "kind": "suppressed_in_position" };
