// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-action decision counts for a run.
 *
 * Covers every action enum the engine emits today: the four open/flat/hold
 * variants and the two directional-close variants. Unknown action strings
 * are ignored — the surface intentionally does not carry an `other`
 * catch-all because the action set is a versioned wire enum, not free text.
 */
export type ActionCounts = { long_open: number, short_open: number, flat: number, hold: number, long_close: number, short_close: number, };
