// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";

export type AddAgentReq = { strategy_id: string, agent_id: string, role: string, 
/**
 * Phase A `AgentRef.activates`. `None` (default) lets the
 * dispatcher pick the slot's first capability — today's behavior.
 * `Some(Capability::Filter)` is rejected; filters are saved JSON
 * artifacts on the strategy, not agent refs.
 */
activates?: Capability, };
