// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddProviderRequest = { name: string, kind: string, base_url: string, api_key_env: string, api_key?: string, };
