// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddProviderRequest = { name: string, kind: string, 
/**
 * Optional — when blank, a kind-aware default is used
 * ("https://api.anthropic.com" for anthropic, "https://api.openai.com/v1"
 * for the canonical "openai" openai-compat, "" for local-candle).
 */
base_url: string, 
/**
 * Optional override for the env var that holds the API key. Defaults to
 * a kind-aware convention so users don't have to pick one.
 */
api_key_env: string, 
/**
 * The actual API key (cleartext over the API). When set, persisted to
 * `$XVN_HOME/secrets/providers.toml` (mode 0600) and exported into the
 * daemon process env under `api_key_env` so the provider works right away.
 * Never logged or returned.
 */
api_key: string | null, };
