// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDiagnostic } from "./ToolDiagnostic";

export type AgentDiagnostics = { role: string, agent_id: string, agent_name: string | null, agent_resolved: boolean, tools: Array<ToolDiagnostic>, };
