// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";

/**
 * One agent's appearance inside a strategy. `agent_id` is an FK to the
 * `Agent` record in the workspace agent library; `role` is the
 * user-defined role this agent plays in this particular strategy. The
 * same agent can appear in different strategies under different role
 * names — role lives on the reference, not the referent.
 */
export type AgentRef = { agent_id: string, role: string,
/**
 * Which capability of the referenced agent this position
 * activates. Phase A field — Phase B's unified dispatcher reads
 * this to pick the slot's handler when an agent advertises more
 * than one capability.
 *
 * `None` (the default) means "let the runtime pick the slot's
 * first capability in `BTreeSet` order" — which is `Trader` for
 * every legacy/pre-033 slot.
 */
activates?: Capability | null, };
