// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentProfile = { id: string, name: string, 
/**
 * Persona tag (`fast-trader`, `reasoning`, `risk`, `research`, or
 * operator-defined). Open enum on the wire and in storage so custom
 * profiles can be added without a migration.
 */
type: string, provider: string, model: string, temperature: number, max_tokens: number, system_prompt: string, enabled: boolean, created_at: string, updated_at: string, };
