// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSlot = { name: string, provider: string, model: string, system_prompt: string, skill_ids: Array<string>, max_tokens: number | null, };
