// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { CheckpointRef } from "./CheckpointRef";

/**
 * One agent's appearance inside a strategy. `agent_id` is an FK to the
 * `Agent` record in the workspace agent library; `role` is the
 * user-defined role this agent plays in this particular strategy. The
 * same agent can appear in different strategies under different role
 * names — role lives on the reference, not the referent.
 */
export type AgentRef = { agent_id: string, role: string, 
/**
 * Which capability of the referenced agent this position
 * activates. Phase A field — Phase B's unified dispatcher reads
 * this to pick the slot's handler when an agent advertises more
 * than one capability.
 *
 * `None` (the default) means "let the runtime pick the slot's
 * first capability in `BTreeSet` order" — which is `Trader` for
 * every legacy/pre-033 slot. Spec Decision 2.
 */
activates?: Capability, 
/**
 * The system prompt for this agent slot in this strategy. A per-strategy
 * copy of the agent library's `system_prompt` — set at strategy creation
 * time and mutated by the optimizer's prose experiments. When empty,
 * the slot has no override and resolves from the agent library at
 * runtime (legacy strategies). Empty strings are omitted from JSON
 * (`skip_serializing_if`) for a compact wire format and backward compat
 * with the old `Option<String>` representation.
 *
 * The optimizer injects the resolved library prompt here before calling the
 * mutator so the LLM sees the full prompt text in the AgentRef JSON block
 * (`serde_json::to_string_pretty(agent)` renders it inline), making it
 * trivially copyable into the `after` field of prose mutations.
 */
prompt: string, 
/**
 * Optional per-strategy override of the referenced agent's trader-slot
 * `(provider/)model`. Same rationale as `prompt_override`. Reserved for the
 * deferred F25 model-swap mutation axis; honored at resolution today so the
 * axis is a pure mutator/validator add later.
 */
model_override?: string, 
/**
 * NEW: when present, this slot runs a local nanochat checkpoint instead of
 * an LLM. Absent (the default) → omitted from the wire so every existing
 * strategy's JSON and content hash is byte-stable.
 */
checkpoint?: CheckpointRef, 
/**
 * NEW: hard-gate (true) vs advisory (false) for nanochat filter slots.
 * None → omitted from wire (default semantics = hard gate for nanochat
 * slots, resolved at dispatch time). Omitted from wire when None.
 */
veto?: boolean, };
