// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Reference to an LLM-context template. v1 ships "compact_trade_context_v1".
 */
export type AgentContextTemplateId = string;
