// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";

export type AgentTemplate = { 
/**
 * Stable identifier (e.g., "single-trader"). Surfaces in URLs as
 * `/agents/new?template=single-trader` once that's wired.
 */
id: string, 
/**
 * Human-readable label shown on the picker card.
 */
name: string, 
/**
 * One-paragraph blurb describing what the template demonstrates.
 */
description: string, 
/**
 * Pre-filled slots the operator can immediately customize.
 */
slots: Array<AgentSlot>, };
