// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputsPolicy } from "./InputsPolicy";
import type { MemoryMode } from "./MemoryMode";

export type AgentSlot = { name: string, provider: string, model: string, system_prompt: string, 
/**
 * Forward-compat hook for the v1.1 skill registry (see
 * `docs/superpowers/plans/2026-05-11-agents-page-v1.md` §Skills).
 * Each entry is a ULID into the workspace skill registry; entries
 * of `kind = tool | prompt_fragment | evaluator` compose onto this
 * slot at runtime. The picker is hidden in v1 until `/agents/skills`
 * ships — but the field is persisted so existing agents survive the
 * registry landing without a schema migration. Not related to the
 * Plan 2b `xvn skill` surface that was removed in ADR 0012.
 */
skill_ids: Array<string>, 
/**
 * Optional operator override for the per-request token budget.
 * `None` means "auto from the selected model" — the dispatcher
 * resolves it via `agents::model_metadata::resolve_max_tokens`.
 * `Some(n)` is honored and clamped to the model's
 * `output_token_ceiling`.
 *
 * Stored in SQLite as a non-null integer with `0` as the sentinel
 * for `None`; the store layer maps between the sentinel and the
 * Rust-side `Option`.
 */
max_tokens: number | null, 
/**
 * QA30 follow-on: optional operator override for the per-step
 * wall-clock budget (Cline runtime). `None` means "no enforcement"
 * — the runtime defaults to `u32::MAX` so a wedged sidecar step
 * would still hang the cycle, but a still-responding slow model
 * is not killed. `Some(n)` is honoured verbatim; the unit is
 * milliseconds.
 *
 * Stored in SQLite as a non-null integer with `0` as the sentinel
 * for `None` (migration 047), matching the `max_tokens` shape so
 * the store-layer 0-as-unset projection can be reused.
 */
max_wall_ms: number | null, 
/**
 * Optional operator override for the sampling temperature
 * forwarded to the provider. `None` lets the provider's default
 * apply (Anthropic ~1.0, OpenAI 1.0). `Some(t)` is passed through
 * verbatim — no clamping. Eval-baseline operators set a low
 * value (e.g. 0.2) when they want reproducible decisions; agent-
 * loop operators leave it unset.
 *
 * Not yet persisted to SQLite (a follow-up migration will add the
 * column). For now the field round-trips through JSON via
 * `#[serde(default)]`; rows loaded from the store always come
 * back as `None`, so existing seeded agents see the provider
 * default until they're re-saved with an explicit value.
 */
temperature: number | null, 
/**
 * Server-computed content digest of `system_prompt`. Format is the
 * lowercase 16-char prefix of `sha256(system_prompt)` — short
 * enough to eyeball in the agents UI, long enough to make
 * accidental collision implausible.
 *
 * The field is `#[serde(default)]` so clients may omit it on POST
 * /PUT bodies; any value the client sends is silently overridden
 * at persist time by `AgentStore::insert_slot`. On the read path
 * the server always returns the persisted value (the empty string
 * only appears on rows persisted before migration 019; the next
 * save through the store backfills it).
 *
 * Wired into observability via `SpanAttributes.prompt_version`
 * (the field already exists; the strategy-assembly hop that
 * threads it from `AgentSlot` → `LLMSlot` → span emission ships
 * in a sibling follow-up so this PR stays foundation-only).
 *
 * See harness audit F-3 (`team/intake/2026-05-18-harness-observability-audit.md`).
 */
prompt_version: string, 
/**
 * How the eval executor sanitizes the seed JSON before the trader
 * LLM sees it. Persisted on the `agent_slots.inputs_policy`
 * column (migration 020). Defaults to `Raw` so existing rows and
 * clients that omit the field keep today's behavior. See
 * harness audit F-6
 * (`team/intake/2026-05-19-eval-traces-end-to-end-audit.md`).
 */
inputs_policy: InputsPolicy, 
/**
 * Optional cap on the number of `bar_history` entries the eval
 * executor surfaces to the trader LLM at each decision. `None`
 * (the migration default) preserves today's behavior — the full
 * `warmup_bars`-sized history slice is sent through. `Some(n)`
 * trims the slice to its most-recent `n` entries before the
 * trader sees it, which keeps the prompt prefix stable across
 * many decisions so provider prompt-caching (Anthropic) can land
 * a hit on the static portion.
 *
 * Persisted as a NULLable INTEGER on `agent_slots.bar_history_limit`
 * (migration 025); the store layer maps NULL ↔ `None` and rejects
 * non-positive ints (mapping `Some(0)` → `None`) so a stray `0`
 * can't silently drop every bar from the trader's view.
 *
 * F-8 (`team/contracts/eval-prompt-cache-and-rolling-window.md`).
 */
bar_history_limit: number | null, 
/**
 * How the dispatcher consults the cortex-memory layer
 * (`xvision-memory`) for this slot. Persisted on the
 * `agent_slots.memory_mode` column (migration 026). Defaults to
 * `Off` so existing rows and clients that omit the field keep
 * today's behavior — the dispatcher does not consult or write the
 * memory store. See the V2D cortex-memory integration plan
 * (`docs/superpowers/plans/2026-05-21-cortex-memory-integration-plan.md`).
 *
 * The ts-rs derive is intentionally omitted in Phase 2 — the
 * `xvision-memory::MemoryMode` enum will be exported through the
 * engine's `ts-export` feature in Phase 4, which is when the
 * frontend gains a UI for this knob.
 */
memory_mode: MemoryMode, 
/**
 * Per-slot opt-out for the `trader-noop-skip` pre-LLM gate
 * (`team/intake/2026-05-21-eval-honesty-and-agent-graph.md`).
 *
 * When `None` (the default) or `Some(true)`, the engine skips the
 * LLM call entirely for any decision cycle where the current
 * `portfolio_state` allows **zero legal open actions** (i.e. the
 * portfolio already holds a position on this asset so both
 * `long_open` and `short_open` are blocked — the only legal action
 * is `hold`). A synthesized trader output with `action: hold`,
 * `conviction: 0`, and `noop_skip` in `justification` is recorded so
 * the trace and eval review surfaces can see that the skip happened.
 *
 * Set to `Some(false)` when you explicitly want the LLM to run even
 * in a zero-legal-actions state (e.g. "what would the model say in
 * a corner case?" analysis). This opt-out is intentional model spend
 * and is honoured without warning.
 *
 * Not yet persisted to SQLite (a follow-up migration will add the
 * column when the UI surfaces this knob). For now the field
 * round-trips through JSON via `#[serde(default)]`; rows loaded
 * from the store come back as `None` which is treated the same as
 * `Some(true)`.
 */
noop_skip: boolean | null, 
/**
 * Tool names this slot is allowed to invoke. Empty means callers may
 * fall back to a strategy-level required tool list for legacy strategy
 * slots; persisted as JSON on `agent_slots.allowed_tools_json`.
 */
allowed_tools: Array<string>, 
/**
 * Per-slot opt-in for **delta-briefing mode** (F41 token-efficiency
 * tail). When `Some(true)`, the trader briefing for bar N+1 is
 * compressed to **only the delta** from bar N's briefing — changed
 * indicators, new fills, regime transitions — rather than the full
 * snapshot. Falls back to the full briefing on cache miss (first
 * bar of a run; the prev briefing wasn't tracked; or the diff
 * would be too sparse to be useful).
 *
 * Defaults to `None` ≡ `Some(false)`. The full-briefing path is
 * byte-identical to pre-F41 behaviour so existing eval runs are
 * unaffected. Operators opt in per slot when they want to lean on
 * provider prompt caching (Anthropic `cache_control`) **and**
 * shrink the variable suffix of the prompt — the two combine to
 * cut per-cycle token spend by ~60% on long horizons.
 *
 * Not yet persisted to SQLite (a follow-up migration will add the
 * column when the UI surfaces this knob). For now the field
 * round-trips through JSON via `#[serde(default)]`; rows loaded
 * from the store come back as `None` (full briefing).
 *
 * See `team/contracts/eval-token-efficiency-tail.md` and
 * `crates/xvision-engine/src/agent/briefing.rs` for the diff shape
 * and `delta(prev, curr)` function.
 */
delta_briefing: boolean | null, };
