// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";

export type Agent = { agent_id: string, name: string, description: string, tags: Array<string>, slots: Array<AgentSlot>, archived: boolean, created_at: string, updated_at: string,
/**
 * If `Some(strategy_id)`, this agent is scoped to a single
 * strategy and hidden from the default workspace agent list
 * (`GET /api/agents`). Persists the "Save as reusable agent"
 * toggle on the strategy editor's inline Filter composer —
 * toggle ON (default) → `None`, toggle OFF → `Some(<id>)`.
 * Migration 036.
 */
scope_strategy_id?: string | null, };
