// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggressor side for a fill — maker vs taker classification.
 *
 * Foundation lands the type as `Option<AggressorSide>` defaulting `None`;
 * `eval-intra-bar-fill-ordering` populates the values.
 */
export type AggressorSide = "taker" | "maker";
