// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlpacaTestReport = { ok: boolean, latency_ms: number,
/**
 * Account status as reported by `/v2/account` (e.g. "ACTIVE").
 * None on failure or when the field is missing from the response.
 */
account_status?: string,
/**
 * Account equity as reported by Alpaca (USD, plain decimal string).
 * None on failure or when the field is missing.
 */
equity?: string,
/**
 * Failure message when `ok` is false. None on success.
 */
error?: string, };
