// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Equity-specific rule violation kinds.
 *
 * All variants serialize / deserialize cleanly (equity stub round-trip
 * through serde). The impl (`AlpacaEquityRules::validate`) is a no-op in v1.
 */
export type AlpacaEquityViolationKind = "pdt_risk_or_rejection" | "extended_hours_not_supported" | "non_marginable_asset" | "short_not_allowed" | "insufficient_buying_power";
