// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a `POST /brokers/alpaca/test-connection` call. Reports
 * whether `/v2/account` responded and surfaces a couple of harmless
 * account fields as a sanity-check signal.
 */
export type AlpacaTestReport = { ok: boolean, latency_ms: number, 
/**
 * Account status as reported by `/v2/account` (e.g. "ACTIVE").
 * None on failure or when the field is missing from the response.
 */
account_status: string | null, 
/**
 * Account equity as reported by Alpaca (USD, plain decimal string).
 * None on failure or when the field is missing.
 */
equity: string | null, 
/**
 * Failure message when `ok` is false. None on success.
 */
error: string | null, };
