// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire type returned by `GET /api/assets`.
 *
 * Each entry combines the per-asset venue mappings from the process-global
 * asset registry with the `enabled` flag populated at whitelist load time.
 */
export type AssetInfo = { 
/**
 * Canonical ticker, e.g. `"BTC"`.
 */
symbol: string, 
/**
 * Coarse category: `"crypto"`, `"stable"`, `"meme"`, `"rwa"`,
 * `"equity"`, `"index"`, `"commodity"`, `"orderly-broker"`.
 */
category: string, 
/**
 * Primary data source: `"alpaca"` or `"orderly-only"`.
 */
data: string, 
/**
 * Venue-specific trading pair / market strings keyed by venue name
 * (`"alpaca"`, `"orderly"`). Absent when the venue is not supported.
 */
venues: { [key: string]: string }, 
/**
 * `true` iff `enabled = true` in the loaded whitelist.
 */
enabled: boolean, };
