// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoOptimizerRunListRequest = { 
/**
 * Exact namespace, e.g. `global` or `agent:<id>`.
 */
namespace: string | null, 
/**
 * Convenience shorthand for `namespace = agent:<id>`.
 */
agent: string | null, limit: bigint | null, offset: bigint | null, };
