// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoOptimizerRunRequest = { 
/**
 * Exact namespace, e.g. `global` or `agent:<id>`.
 */
namespace: string | null, 
/**
 * Convenience shorthand for `namespace = agent:<id>`.
 */
agent: string | null, 
/**
 * Optional Observation provenance filters.
 */
scenario_id: string | null, run_id: string | null, 
/**
 * Candidate Pattern text for this first deterministic pass. Later
 * phases replace this with an LLM proposal step before promotion.
 */
pattern_text: string, 
/**
 * If true, the Pattern is recall-active immediately; default is
 * staged so a later numeric gate can promote it.
 */
active: boolean, limit: bigint | null, min_observations: number | null, };
