// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshPolicy } from "./RefreshPolicy";

export type BarCachePolicy = { cache_key: string, refresh_policy: RefreshPolicy, data_fetched_at: string | null, };
