// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strategy outperformance (return_pct delta) versus each of the five baselines.
 * Positive = the strategy beat the baseline on raw total return.
 */
export type BaselineRelative = { buy_hold: number, always_flat: number, simple_trend: number, simple_mean_reversion: number, 
/**
 * Defaults to `0.0` when deserializing legacy rows that predate this field.
 */
random_direction: number, };
