// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaselineMetrics } from "./BaselineMetrics";
import type { BaselineRelative } from "./BaselineRelative";

/**
 * All five automatic baselines computed over the same bar slice the strategy
 * saw, plus the per-baseline return delta (`strategy_return_pct −
 * baseline_return_pct`).
 *
 * Serialized as `{"baselines": ..., "relative_to": ...}` and packed into
 * `MetricsSummary.baselines` (stored in the existing `metrics_json` column).
 * No DB migration required; old rows deserialize with `baselines: None`.
 */
export type BaselinesReport = { buy_hold: BaselineMetrics, always_flat: BaselineMetrics, simple_trend: BaselineMetrics, simple_mean_reversion: BaselineMetrics, 
/**
 * Coin-flip long/short at 100 bps per bar, seeded for reproducibility.
 * Defaults to `BaselineMetrics { return_pct: 0.0, sharpe: 0.0 }` when
 * deserializing legacy rows that predate this field.
 */
random_direction: BaselineMetrics, 
/**
 * `strategy_return_pct − baseline_return_pct` for each baseline.
 */
relative_to: BaselineRelative, };
