// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-baseline performance numbers for one of the four automatic baselines.
 *
 * Stored inside `MetricsSummary.baselines` (packed into `metrics_json` on
 * the `eval_runs` row). No separate DB column or migration is required —
 * old rows without the key simply deserialize with `baselines: None`.
 */
export type BaselineMetrics = { 
/**
 * Total return as a percentage of starting capital. E.g. `6.80` means +6.80%.
 */
return_pct: number, 
/**
 * Annualised Sharpe ratio. `0.0` when flat or < 2 bars.
 */
sharpe: number, };
