// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionCounts } from "./ActionCounts";

/**
 * Behavior summary derived from a run's decision rows.
 */
export type BehaviorSummary = { 
/**
 * Fraction of all decisions that are `flat` or `hold` (0.0–1.0).
 */
flat_rate: number, 
/**
 * Count of `long_open` + `short_open` decisions.
 */
trades_opened: number, 
/**
 * Consecutive open-direction flips without a flat between them.
 */
direct_flips: number, 
/**
 * Mean bars between an `open` and the next `flat` for the same asset.
 * `None` when there are no completed round-trips.
 */
avg_bars_held: number | null, 
/**
 * Opens immediately following a `flat` with `pnl_realized < 0`.
 */
reentries_after_loss: number, 
/**
 * `flat` decisions with `pnl_realized < 0` (closed at a loss).
 */
exits_on_invalidation: number, 
/**
 * Heuristic label for the most likely failure mode.
 */
primary_failure_mode: string, 
/**
 * Per-action decision counts. Appended 2026-05-22 for the
 * `cli-report-actions-and-tokens` track. `Default` is the all-zeroes
 * counts struct, so older callers deserializing payloads without this
 * field still parse — `#[serde(default)]` keeps the JSON shape
 * backward-compatible.
 */
action_counts: ActionCounts, 
/**
 * Number of same-direction "stacking" opens on the same asset without
 * an intervening close (see module doc).
 */
repeated_opens: number, };
