// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrokerViolationSeverity } from "./BrokerViolationSeverity";

/**
 * A single broker-rule violation. Produced by `BrokerRuleSet::validate`
 * and written into the findings JSONL as a `broker_rule_violation` kind.
 *
 * `specific_rule` names the exact check that fired (matches the
 * `produced_by_check` field in the finding: `"broker:<specific_rule>"`).
 */
export type BrokerRuleViolation = { 
/**
 * Slug identifying the exact rule that fired. Examples:
 * `"unsupported_order_type"`, `"min_order_size_violation"`.
 */
specific_rule: string, 
/**
 * Human-readable explanation.
 */
message: string, 
/**
 * Severity level: `"warning"` (non-blocking but suspect) or `"critical"`
 * (would be hard-rejected at the venue).
 */
severity: BrokerViolationSeverity, };
