// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrokerEntry } from "./BrokerEntry";

export type BrokersReport = { alpaca: BrokerEntry, orderly: BrokerEntry, byreal: BrokerEntry, byreal_spot: BrokerEntry, degen_arena: BrokerEntry, hyperliquid: BrokerEntry, };
