// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialRef } from "./CredentialRef";

export type BrokerEntry = { 
/**
 * Display name ("Alpaca", "Orderly Network").
 */
name: string, 
/**
 * Stable kind tag for the frontend ("alpaca" | "orderly").
 */
kind: string, 
/**
 * Per-required-env-var presence; values are never returned.
 */
credentials: Array<CredentialRef>, 
/**
 * Roll-up: are *all* required credentials set?
 */
configured: boolean, 
/**
 * Optional base URL; surfaces the override if set, else default.
 */
base_url: string | null, 
/**
 * Short note for v1 ("paper trading", "live only — post-v1", etc.).
 */
note: string | null, };
