// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialRef } from "./CredentialRef";

export type BrokerEntry = { 
/**
 * Display name ("Alpaca", "Orderly Network").
 */
name: string, 
/**
 * Stable kind tag for the frontend ("alpaca" | "orderly").
 */
kind: string, 
/**
 * Per-required-env-var presence; values are never returned.
 */
credentials: Array<CredentialRef>, 
/**
 * Roll-up: env vars OR stored creds are sufficient to connect.
 */
configured: boolean, 
/**
 * True when this broker has stored credentials under
 * `$XVN_HOME/secrets/brokers.toml`. Independent of env-var state —
 * stored creds win at runtime, but env state is still surfaced for
 * debuggability.
 */
stored: boolean, 
/**
 * Last 4 of the stored key id, if stored. Safe to display.
 */
stored_key_id_suffix: string | null, 
/**
 * Optional base URL; surfaces the override if set, else default.
 */
base_url: string | null, 
/**
 * Short note for v1 ("paper trading", "live only — post-v1", etc.).
 */
note: string | null, };
