// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache status for a scenario's bar window.
 */
export type CacheStatus = { "type": "FullyCached", bar_count: number, fetched_at: string, } | { "type": "PartiallyCached", fetched_count: number, expected_count: number, } | { "type": "NotCached", expected_count: number, };
