// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One capability class an agent slot can play in a strategy pipeline.
 *
 * Closed set per Decision 1 of the capability-first agent model spec.
 * Adding a new variant is a schema change — the wave-coordinator must
 * reserve a migration row + update the dispatcher.
 */
export type Capability = "trader" | "filter" | "router";
