// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How capital is shared across assets in a run.
 */
export type CapitalMode = "pooled" | "per_asset";
