// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelEntry } from "./ModelEntry";

/**
 * One provider's worth of catalog data, plus provenance.
 *
 * `fetched_at` is the source-of-truth for staleness checks. The cache
 * layer uses this to decide when to refresh; consumers can also display
 * "fetched N minutes ago" in the UI.
 */
export type Catalog = { 
/**
 * Matches `ProviderEntry.name`. The provider this catalog belongs
 * to — not the model vendor (a single OpenRouter provider entry
 * can list models from many vendors).
 */
provider: string, 
/**
 * Wall-clock time of the most recent successful fetch, in UTC.
 * Cache freshness is computed against this.
 */
fetched_at: string, 
/**
 * The HTTP URL the fetcher hit. Stored for transparency and to
 * help diagnose unexpected catalog contents.
 */
source_url: string, 
/**
 * All models the provider returned, in the order the API gave them.
 * We don't sort or dedupe — preserving provider-side order avoids
 * surprising the UI when the upstream introduces new fields.
 */
models: Array<ModelEntry>, };
