// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldMarker } from "./HoldMarker";
import type { TradeMarker } from "./TradeMarker";
import type { VetoMarker } from "./VetoMarker";

export type ChartMarkers = { trades: Array<TradeMarker>, vetoes: Array<VetoMarker>, holds: Array<HoldMarker>, };
