// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Equity point for the chart payload (distinct from `api::eval::EquityPoint`
 * which uses `equity_usd` and `timestamp` for the run-detail API).
 */
export type ChartEquityPoint = { time: number, equity_usd: number, };
