// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineAction } from "./InlineAction";

export type ChatActionPayload = { action_id: string, title: string, body: string, confirm: InlineAction, cancel: InlineAction | null, };
