// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlinePoint } from "./InlinePoint";

export type ChatRunListItem = { rank: number, run_id: string, strategy_id: string | null, scenario: string | null, return_pct: number | null, sharpe: number | null, sparkline: Array<InlinePoint> | null, };
