// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineAction } from "./InlineAction";
import type { InlineMetric } from "./InlineMetric";

export type ChatStrategyPayload = { strategy_id: string, title: string, subtitle: string | null, status: string | null, metrics: Array<InlineMetric>, tags: Array<string>, actions: Array<InlineAction>, };
