// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference from a strategy's `AgentRef` to a trained nanochat checkpoint.
 * When `Some`, the slot runs a local nanochat model instead of an LLM.
 * Mutually exclusive with `model_override` at strategy-save validation time.
 * Absent (the default) → omitted from wire → all existing strategy JSON and
 * content hashes are byte-stable.
 */
export type CheckpointRef = { 
/**
 * FK → `trained_models.model_id` (ULID).
 */
model_id: string, };
