// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparisonEquitySample } from "./ComparisonEquitySample";

export type ComparisonEquityCurve = { run_id: string, samples: Array<ComparisonEquitySample>, };
