// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BehaviorSummary } from "./BehaviorSummary";
import type { MetricsSummary } from "./MetricsSummary";
import type { RunMode } from "./RunMode";
import type { RunStatus } from "./RunStatus";

export type ComparisonRunSummary = { id: string, agent_id: string, scenario_id: string, mode: RunMode, status: RunStatus, started_at: string, completed_at: string | null, metrics: MetricsSummary | null, error: string | null, 
/**
 * Derived action-distribution + behaviour summary for this run.
 * Populated by `compare_runs`; `None` only when the decision store
 * query fails for this run (treated as best-effort, not fatal).
 */
behavior: BehaviorSummary | null, 
/**
 * SHA-256 hex digest of the Parquet bytes used for this run.
 * `None` for pre-migration rows.
 */
bars_content_hash: string | null, 
/**
 * SHA-256 hex digest of the canonical DataManifest for this run.
 * `None` for pre-migration rows.
 */
manifest_canonical: string | null, 
/**
 * Net return after deducting LLM inference cost. `None` for old runs
 * without pricing data or when the model isn't in the pricing catalog.
 * Mirror of `MetricsSummary::net_return_pct` hoisted to the comparison
 * arm so the compare view can render a Net column without deep-reading
 * the full metrics blob.
 */
net_return_pct: number | null, 
/**
 * Sum of `model_calls.input_token_count` for this run. `None` when
 * the run produced no model_calls (legacy / pre-observability rows)
 * or none of them recorded token counts. Appended 2026-05-22 for
 * `cli-report-actions-and-tokens`.
 */
input_tokens: bigint | null, 
/**
 * Sum of `model_calls.output_token_count`.
 */
output_tokens: bigint | null, 
/**
 * Sum of `model_calls.cost_usd`. Not a recomputation — purely a
 * rollup of the populated column. `None` when every contributing
 * row had `cost_usd = NULL` or there were no contributing rows.
 */
cost_usd_estimate: number | null, 
/**
 * `true` iff every model_call contributing to `cost_usd_estimate`
 * had a non-null `cost_usd`. When `false`, the estimate is a strict
 * lower bound. Defaults to `true` for legacy payloads where no
 * model_calls were aggregated — but in that case the cost itself is
 * `None`, so the flag carries no false signal.
 */
cost_estimate_complete: boolean, 
/**
 * Wall-clock duration (`completed_at - started_at`) in milliseconds.
 * `None` for runs that haven't terminated, or pre-migration rows.
 */
wall_clock_ms: bigint | null, };
