// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartBar } from "./ChartBar";
import type { CompareRunSeries } from "./CompareRunSeries";

export type CompareChartPayload = { runs: Array<CompareRunSeries>, shared_scenario: string | null, price_backdrop: Array<ChartBar> | null, };
