// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSummary } from "./MetricsSummary";
import type { RunMode } from "./RunMode";
import type { RunStatus } from "./RunStatus";

export type ComparisonRunSummary = { id: string, agent_id: string, scenario_id: string, mode: RunMode, status: RunStatus, started_at: string, completed_at: string | null, metrics: MetricsSummary | null, error: string | null, };
