// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparisonEquityCurve } from "./ComparisonEquityCurve";
import type { ComparisonRunSummary } from "./ComparisonRunSummary";
import type { Finding } from "./Finding";

export type ComparisonReport = { runs: Array<ComparisonRunSummary>, equity_curves: Array<ComparisonEquityCurve>, findings: Array<Finding>, };
