// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ChartEquityPoint } from "./ChartEquityPoint";

export type CompareRunSeries = { run_id: string, label: string, scenario_id: string, equity: Array<ChartEquityPoint>, };
