// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Operand } from "./Operand";
import type { Operator } from "./Operator";

export type Condition = { lhs: Operand, op: Operator, rhs: Operand, };
