// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionItem } from "./ConditionItem";

/**
 * Logical tree above leaf `Condition`s. Serde `rename_all = "snake_case"`
 * produces the `all`/`any` tag expected by the DSL (`[[filter.conditions.all]]`).
 *
 * Items may be flat `Leaf` conditions or one level of nested `Group`.
 */
export type ConditionTree = { "all": Array<ConditionItem> } | { "any": Array<ConditionItem> };
