// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";

/**
 * Logical tree above leaf `Condition`s. v1 is a flat `All` or `Any`; the
 * spec's TOML example uses `[[filter.conditions.all]]`. Serde
 * `rename_all = "snake_case"` produces that tag.
 */
export type ConditionTree = { "all": Array<Condition> } | { "any": Array<Condition> };
