// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { ConditionGroup } from "./ConditionGroup";

/**
 * A top-level item in a `ConditionTree`: either a flat `Leaf` condition
 * or a nested `ConditionGroup` (max 1 level deep by type construction).
 *
 * Serializes as untagged (Leaf: `{lhs,op,rhs}`, Group: `{all:[...]}` /
 * `{any:[...]}`). Deserialization uses a custom visitor that peeks at the
 * first map key to choose the variant — this avoids swallowing Operand/
 * Operator parse errors the way `#[serde(untagged)]` would.
 */
export type ConditionItem = { "Leaf": Condition } | { "Group": ConditionGroup };
