// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";

/**
 * Inner condition group — non-recursive. Holds only flat `Condition`s.
 * Depth > 1 is structurally impossible: `ConditionGroup` contains
 * `Vec<Condition>`, not `Vec<ConditionItem>`.
 */
export type ConditionGroup = { "all": Array<Condition> } | { "any": Array<Condition> };
