// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Windowed cross-source spend rollup. The FE budget strip builds on this exact
 * shape: each `*_usd` field is `null` when its source has no cost data.
 */
export type CostRollupResponse = { 
/**
 * Echo of the validated `?since` lower bound (RFC-3339, UTC).
 */
since: string, 
/**
 * Combined eval/agent-run + optimizer spend in the window. `null` when
 * BOTH component sources are unknown; otherwise the sum of the known
 * components (an unknown half does not NULL out a known half).
 */
spend_usd: number | null, 
/**
 * Eval + agent-run inference cost (token cost) over runs started in the
 * window. `null` (unknown) when no priced call exists.
 */
eval_cost_usd: number | null, 
/**
 * Optimizer (autooptimizer cycle) cost over cycles in the window. `null`
 * (unknown) when no metered cycle exists.
 */
optimizer_cost_usd: number | null, 
/**
 * Operator-set daily budget cap, or `null` when UNSET (render em-dash,
 * never a faked ceiling).
 */
daily_cap_usd: number | null, };
