// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The persisted operator-set daily budget cap. `daily_cap_usd` is `null` when
 * UNSET.
 */
export type CostBudgetResponse = { daily_cap_usd: number | null, };
