// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetClass } from "./AssetClass";
import type { CalendarRef } from "./CalendarRef";
import type { DataSource } from "./DataSource";
import type { QuoteCurrency } from "./QuoteCurrency";
import type { ReplayMode } from "./ReplayMode";
import type { ScenarioSource } from "./ScenarioSource";
import type { TimeWindow } from "./TimeWindow";
import type { VenueSettings } from "./VenueSettings";

/**
 * Request to create a new scenario. Caller fills in every field; the
 * engine assigns `id`, `created_at`, `created_by`, and `bar_cache_policy`.
 */
export type CreateScenarioRequest = { display_name: string, description: string, asset_class: AssetClass, quote_currency: QuoteCurrency, time_window: TimeWindow, capital: { initial: number, currency: string }, granularity: string, timezone: string, calendar: CalendarRef, 
/**
 * QA31: chat-agent callers (Gemini Flash etc.) repeatedly omit
 * `venue` because the tool schema declares it as required but its
 * shape is opaque to the model. Default to a sensible Alpaca
 * preset (matches `VenueSettings::default()` and the wizard
 * normalizer's `default_venue_json`) so the request deserializes
 * even when the caller didn't supply it. The wizard normalizer
 * still pre-fills the field where it can; this is the
 * belt-and-suspenders fallback.
 */
venue: VenueSettings, data_source: DataSource, replay_mode: ReplayMode, tags: Array<string>, notes: string | null, parent_scenario_id: string | null, source: ScenarioSource, 
/**
 * Pre-window context bars. `None` → `DEFAULT_WARMUP_BARS` (200).
 * Stored inside `body_json` on the scenario row.
 */
warmup_bars: number | null, };
