// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillKind } from "./SkillKind";

export type CreateSkillRequest = { name: string, description: string, kind: SkillKind, config: Record<string, unknown>, };
