// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";

export type CreateAgentRequest = { name: string, description: string, tags: Array<string>, slots: Array<AgentSlot>,
/**
 * Optional strategy id this agent is scoped to. Strategy editor's
 * inline Filter composer sets this when the "Save as reusable
 * agent" toggle is OFF — the resulting agent stays hidden from
 * the workspace list. Migration 036.
 */
scope_strategy_id?: string | null, };
