// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";

export type CreateAgentRequest = { name: string, description: string, tags: Array<string>, slots: Array<AgentSlot>, };
