// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialRef = { 
/**
 * Env var name (e.g. "APCA_API_KEY_ID"). Safe to display.
 */
env_var: string, 
/**
 * True if the env var is set (and non-empty). Value never leaks.
 */
is_set: boolean, };
