// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonStatus } from "./DaemonStatus";

export type DaemonReport = { status: DaemonStatus, 
/**
 * Operator-facing explanation for the current state.
 */
note: string, 
/**
 * Plan that will activate the daemon, or `None` if it's available now.
 */
deferred_to_plan: string | null, };
