// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdjustmentMode } from "./AdjustmentMode";
import type { WalkModel } from "./WalkModel";

export type DataSource = { "type": "AlpacaHistorical", feed: string | null, adjustment: AdjustmentMode, } | { "type": "SyntheticWalk", seed: bigint, model: WalkModel, };
