// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionRowDto = { decision_index: number, timestamp: string, asset: string, action: string, conviction: number | null, justification: string | null, reasoning: string | null, order_size: number | null, fill_price: number | null, fill_size: number | null, fee: number | null, pnl_realized: number | null, delayed: boolean, };
