// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * Per-decision LLM provenance record — attaches alongside the fill outcome
 * in the `decisions.jsonl` sidecar.
 *
 * All fields default to zero-values so old runs (schema_version="1") that
 * lack these fields deserialize without error.
 */
export type DecisionTrace = { 
/**
 * Model identifier used for this decision (e.g. `"claude-opus-4-7"`).
 */
model_id: string, 
/**
 * SHA-256 hex digest of the prompt template string. Stable across runs
 * using the same prompt version; changes on any prompt edit.
 */
prompt_template_hash: string, 
/**
 * Sampling temperature applied to this decision.
 */
temperature: number, 
/**
 * `top_p` applied to this decision.
 */
top_p: number, 
/**
 * Random seed, if deterministic sampling was requested.
 */
seed: bigint, 
/**
 * Input tokens consumed (prompt + system).
 */
tokens_in: number, 
/**
 * Output tokens generated (completion).
 */
tokens_out: number, 
/**
 * Wall-clock LLM round-trip time in milliseconds.
 */
latency_ms: number, 
/**
 * Tools invoked during this decision cycle.
 */
tools_called: Array<ToolCall>, };
