// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CT5 per-tick capital block (Epic s78 Wave 3, §4). Carried on
 * [`RunChartEvent::DeploymentMetrics`] over the `RunEventBus` and surfaced as
 * the deployment SSE `event: metrics` frame.
 *
 * HONESTY MANDATE (§8.1 / §8.9): every capital/P&L field is `Option` — an
 * unsourceable value serializes as `null` (rendered "—" / "no data" in the UI),
 * **NEVER** a fabricated `0`. These are the SAME honest book/execution-sourced
 * numbers the 5s poll surfaces — no value is ever sourced from `agent_runs` or
 * eval summaries. `null`-skipping is intentional: a field with no real data is
 * OMITTED from the frame, not coerced to zero.
 */
export type DeploymentMetricsTick = { 
/**
 * Bar/decision timestamp (unix seconds) this tick is keyed at. Shared time
 * axis with the `Equity` ticks.
 */
time: number, 
/**
 * Pooled NAV at this tick (`book.equity(marks)`). Always present on a live
 * tick — the equity sample is what triggers the emission.
 */
equity_usd: number, 
/**
 * `(peak_equity - equity) / peak_equity * 100` from the in-memory per-session
 * peak. `None` when no positive peak exists yet (NOT a faked `0`).
 */
drawdown_pct: number | null, 
/**
 * Σ open-position notional (`PortfolioBook::open_legs()`). `None` pre-first-fill.
 */
deployed_capital_usd: number | null, 
/**
 * `book.equity(marks) - initial - book.realized()`. `None` when unavailable.
 */
unrealized_pnl_usd: number | null, 
/**
 * `book.realized()`. `None` when there is no fill history yet (NOT `0`).
 */
realized_pnl_usd: number | null, 
/**
 * Headroom before the enforced daily-loss kill (§6.2). `None` when no kill
 * policy / no day baseline yet.
 */
daily_loss_limit_remaining_usd: number | null, 
/**
 * Cumulative filled-trade count for the run.
 */
n_trades: number, };
