// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paper vs. live (real-money) venue. Sourced from `live_config.venue_label`,
 * NOT inferred from `agent_runs`. `VenueLabel::Live` is rejected at validation
 * today, so in Wave 3 every deployment renders `Paper` in practice; both
 * values exist for forward-compatibility.
 */
export type DeploymentMode = "paper" | "live";
