// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who queued a run — the deployment-source discriminator backing CT5's
 * `LiveDeploymentSummary.source` and `awm`'s Cancel-gate (only `Human`-sourced
 * runs may be cancelled from the dashboard strip). Persisted in the
 * `eval_runs.source` column (migration 065, DB default `'human'`). Set at
 * queue time: the operator queue path (POST /api/eval/runs) keeps the
 * `Human` default; the autooptimizer eval adapter sets `Optimizer`. The
 * strategy `agent_id` is NOT a reliable discriminator (the optimizer reuses
 * `strategy.manifest.id`), so this explicit column is required. See
 * docs/superpowers/specs/2026-06-13-ct5-live-deployment-contract.md §9.2.
 */
export type DeploymentSource = "human" | "optimizer";
