// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator-facing lifecycle of a deployment, derived from `eval_runs.status`
 * overlaid with the per-run + global pause flags. Live runs are long-lived;
 * `Completed`/`Cancelled` for a live run means the operator stopped it.
 *
 * Derivation (§2.2): `Queued → Starting`; `Running` (or `Paused` if the run
 * is paused OR the global safety gate is paused); `Completed`/`Cancelled →
 * Stopped`; `Failed → Failed`. A paused system NEVER renders green "running"
 * (§8) — the global safety pause forces the effective status to `Paused`.
 */
export type DeploymentStatus = "starting" | "running" | "paused" | "stopped" | "failed";
