// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndicatorPoint } from "./IndicatorPoint";

export type DonchianSeries = { upper: Array<IndicatorPoint>, lower: Array<IndicatorPoint>, };
