// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Predicate evaluated against an upstream agent's `FilterSignal.payload`
 * to decide whether a `PipelineEdge` fires. Closed set per Decision 5
 * of the capability-first agent model spec.
 *
 * The serde tag is `snake_case` so on-disk JSON reads the lowercase
 * variant name verbatim:
 *
 * ```json
 * { "eq": { "signal_field": "regime", "value": "trend" } }
 * { "any": [ { "eq": { ... } }, { "eq": { ... } } ] }
 * ```
 */
export type EdgePredicate =
  | { "eq": { signal_field: string, value: unknown, } }
  | { "neq": { signal_field: string, value: unknown, } }
  | { "gte": { signal_field: string, value: unknown, } }
  | { "lte": { signal_field: string, value: unknown, } }
  | { "in": { signal_field: string, values: unknown[], } }
  | { "all": Array<EdgePredicate> }
  | { "any": Array<EdgePredicate> }
  | { "not": EdgePredicate };
