// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectiveProviderModel } from "./EffectiveProviderModel";

/**
 * Canonical view of one provider — combines the persisted `ProviderEntry`,
 * secret/env presence, and the operator's `enabled_models` curation into
 * the answer to "is this `(provider, model)` launchable right now?".
 *
 * Returned by [`effective_providers`]; the same shape backs:
 * - `xvn provider list --effective` (CLI)
 * - the dashboard's `/api/settings/providers` handler (via `list`)
 * - the `xvn doctor` `providers` block
 * - eval-launch refusal in `crate::api::eval::resolve_provider`
 *
 * No other code path may independently compute `launchable`. If a new
 * surface needs the answer, route it through `effective_providers` so
 * the CLI / dashboard / eval-launch verdicts stay byte-identical.
 */
export type EffectiveProvider = { provider: string, 
/**
 * Stable string form — `"anthropic" | "openai-compat" | "local-candle" | "ollama" | "llama-cpp" | "vllm"`.
 */
kind: string, base_url: string, 
/**
 * Env var holding the API key. Empty string for no-auth endpoints.
 */
api_key_env: string,
/**
 * The env var the daemon reads this provider's key from BY CONVENTION
 * (`default_api_key_env_for`), independent of whether the operator has
 * overridden `api_key_env`. Surfaced so `provider list` / error messages
 * can NAME the variable an operator must export when a key is missing
 * (QA U8). Empty for no-auth local kinds.
 */
expected_api_key_env: string,
/**
 * Whether the provider is enabled in the workspace config. Today this
 * is always `true` for every non-synthetic row — there is no separate
 * `enabled` toggle — but the field is surfaced so future toggles plug
 * in without breaking JSON consumers.
 */
enabled: boolean, 
/**
 * True iff an API key for this provider is materialized (stored
 * secret, env-exported, or unnecessary because the kind is no-auth).
 */
has_key: boolean, 
/**
 * Per-model launch verdict, one entry per id in `enabled_models`.
 * Empty when the operator hasn't curated a model list yet.
 */
models: Array<EffectiveProviderModel>, 
/**
 * Roll-up verdict — `enabled && has_key && (kind == LocalCandle || at least one model enabled)`.
 * The single source of truth for "can the operator launch eval against
 * this provider right now". Eval-launch refusal turns on the same
 * predicate (see `ProviderUnavailableReason`).
 */
launchable: boolean, };
