// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EffectiveProviderModel = { id: string, 
/**
 * True iff this model id appears in the provider's `enabled_models`
 * list. All entries in `EffectiveProvider::models` are derived from
 * that list, so today every entry is `enabled = true` — the field is
 * kept on the wire so a future "disable individual models" toggle
 * can ship without an API shape change.
 */
enabled: boolean, };
