// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunMode } from "./RunMode";

export type EvalRunRequest = { 
/**
 * Strategy bundle id (the `agent_id` returned by `api::strategy::list`).
 */
agent_id: string, 
/**
 * Scenario id from `canonical_scenarios()` (e.g. `crypto-bull-q1-2025`).
 */
scenario_id: string, 
/**
 * Run mode. `Paper` drives an `AlpacaPaperSurface` against real Alpaca
 * paper credentials; `Backtest` replays the scenario's parquet fixture
 * in-process without any broker.
 */
mode: RunMode, 
/**
 * Optional per-run override of bundle.mechanical_params. Persisted as
 * `eval_runs.params_override_json`.
 */
params_override: Record<string, unknown> | null, };
