// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-run caps. Every field is optional; `None` means "no cap".
 *
 * Backend payload of the launch verb (`xvn eval run --max-decisions …`).
 * Threaded through `EvalRunRequest` → executor builder.
 */
export type EvalLimits = { 
/**
 * Max number of decision cycles the strategy may produce. Each
 * cadence-gated bar that the trader emits a decision for counts
 * as one. Warmup bars never count.
 */
max_decisions: number | null, 
/**
 * Max cumulative input tokens across all model calls in the run.
 */
max_input_tokens: number, 
/**
 * Max cumulative output tokens across all model calls in the run.
 */
max_output_tokens: number, 
/**
 * Max wall-clock seconds the run may take from start to terminal.
 * Serialized as seconds for wire stability across language clients.
 */
max_wall_clock_secs: number, 
/**
 * When `true`, an `max_input_tokens` breach lands the run as
 * `Cancelled`; when `false`, that input-token breach is logged but
 * the run continues (advisory mode).
 *
 * NOTE (strict output cap): `max_output_tokens` no longer respects
 * this flag — when `max_output_tokens` IS set it is ALWAYS a hard
 * cap (a runaway output is misconfiguration, not something to log
 * and continue). This flag now only gates `max_input_tokens`.
 * `max_decisions` and `max_wall_clock_secs` are, as before, always
 * hard caps.
 */
cancel_on_token_limit: boolean, 
/**
 * Flag decisions as delayed when the decision bar's age exceeds
 * this many milliseconds. Only for live/forward-test mode.
 * `None` = never flag (all decisions accepted, none delayed).
 */
stale_data_max_age_ms?: number, 
/**
 * Hang belt: cancel an agent that has been running longer than
 * this many milliseconds without producing a decision.
 * Only for live/forward-test mode. Opt-in.
 */
max_agent_ms?: number, 
/**
 * Maximum consecutive skips before emitting a Degraded health
 * event. Default 5. Only for live/forward-test mode.
 */
max_consecutive_skips: number, };
