// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvalLimits } from "./EvalLimits";
import type { ProviderOverride } from "./ProviderOverride";
import type { RunMode } from "./RunMode";

export type EvalRunRequest = { 
/**
 * Strategy agent id returned by `api::strategy::list`.
 */
agent_id: string, 
/**
 * Scenario id from `canonical_scenarios()` (e.g. `crypto-bull-q1-2025`).
 */
scenario_id: string, 
/**
 * Run mode. `Backtest` replays the scenario's parquet fixture
 * in-process without any broker. `Live` is reserved for live execution.
 */
mode: RunMode, 
/**
 * Optional per-run override of `Strategy.mechanical_params`. Persisted as
 * `eval_runs.params_override_json`.
 */
params_override: Record<string, unknown> | null, 
/**
 * Optional per-run hard caps (decisions / token totals / wall-clock).
 * Breach lands the run as `Cancelled` with a stable reason string in
 * `error`. See `crate::eval::limits::EvalLimits` for shape + semantics.
 * `None` (or every field None) is the pre-limits behavior.
 */
limits: EvalLimits | null, 
/**
 * When `true`, skip the provider reachability preflight and launch the
 * run regardless of provider state. For offline-development scenarios
 * and CI replay only — the default (`false`) is "preflight on" and
 * is the safe production default.
 *
 * CLI: `--skip-preflight`. Dashboard: `skip_preflight: Option<bool>`.
 * When skipped, a `warn`-severity `supervisor_notes` row is written
 * immediately after run creation so the audit trail is honest.
 */
skip_preflight: boolean, 
/**
 * Optional per-launch override of the strategy's bound `(provider,
 * model)`. When set, the override is resolved through
 * `effective_providers::resolve_provider`; if the override is
 * unreachable (key_missing, provider_disabled, model_disabled,
 * provider_unknown) the launch refuses with the typed `reason`.
 *
 * The override does NOT mutate the strategy on disk — it is a
 * per-run swap. Hard limits in `EvalLimits` still apply. CLI:
 * `--provider <X> --model <Y>` (both required together).
 *
 * Wave B #5: `cli-eval-model-override`.
 */
provider_override: ProviderOverride | null, };
