// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-run caps. Every field is optional; `None` means "no cap".
 *
 * Backend payload of the launch verb (`xvn eval run --max-decisions …`).
 * Threaded through `EvalRunRequest` → executor builder.
 */
export type EvalLimits = { 
/**
 * Max number of decision cycles the strategy may produce. Each
 * cadence-gated bar that the trader emits a decision for counts
 * as one. Warmup bars never count.
 */
max_decisions: number | null, 
/**
 * Max cumulative input tokens across all model calls in the run.
 */
max_input_tokens: bigint | null, 
/**
 * Max cumulative output tokens across all model calls in the run.
 */
max_output_tokens: bigint | null, 
/**
 * Max wall-clock seconds the run may take from start to terminal.
 * Serialized as seconds for wire stability across language clients.
 */
max_wall_clock_secs: bigint | null, 
/**
 * When `true`, a token-cap breach lands the run as `Cancelled`
 * with a breach reason; when `false`, the breach is logged but
 * the run continues (advisory mode). Decisions/wall-clock breaches
 * always cancel — only token caps respect this flag.
 */
cancel_on_token_limit: boolean, };
