// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvalLimits } from "./EvalLimits";
import type { LiveConfig } from "./LiveConfig";
import type { ProviderOverride } from "./ProviderOverride";
import type { ReviewModel } from "./ReviewModel";
import type { RunMode } from "./RunMode";

export type EvalRunRequest = {
/**
 * Strategy agent id returned by `api::strategy::list`.
 */
agent_id: string,
/**
 * Scenario id from `canonical_scenarios()` (e.g. `crypto-bull-q1-2025`).
 */
scenario_id: string,
/**
 * Run mode. `Backtest` replays the scenario's parquet fixture in-process
 * without any broker. `Live` is routed to `Executor::live(...)`, which
 * currently returns a not-implemented error pending the
 * `live-bar-source-alpaca` track + the Phase 3 launch endpoint.
 */
mode: RunMode,
/**
 * Optional free-form per-run config bag, persisted verbatim as
 * `eval_runs.params_override_json`. Used as part of the run's dedup
 * fingerprint and read by the watchdog (e.g. `max_run_duration_secs`).
 */
params_override: Record<string, unknown> | null,
/**
 * Required for `mode = live`. Backtest runs must leave this unset.
 */
live_config: LiveConfig | null,
/**
 * Optional per-run hard caps (decisions / token totals / wall-clock).
 * Breach lands the run as `Cancelled` with a stable reason string in
 * `error`. See `crate::eval::limits::EvalLimits` for shape + semantics.
 * `None` (or every field None) is the pre-limits behavior.
 */
limits: EvalLimits | null,
/**
 * When `true`, skip the provider reachability preflight and launch the
 * run regardless of provider state. For offline-development scenarios
 * and CI replay only — the default (`false`) is "preflight on" and
 * is the safe production default.
 *
 * CLI: `--skip-preflight`. Dashboard: `skip_preflight: Option<bool>`.
 * When skipped, a `warn`-severity `supervisor_notes` row is written
 * immediately after run creation so the audit trail is honest.
 */
skip_preflight: boolean,
/**
 * Optional per-launch override of the strategy's bound `(provider,
 * model)`. When set, the override is resolved through
 * `effective_providers::resolve_provider`; if the override is
 * unreachable (key_missing, provider_disabled, model_disabled,
 * provider_unknown) the launch refuses with the typed `reason`.
 *
 * The override does NOT mutate the strategy on disk — it is a
 * per-run swap. Hard limits in `EvalLimits` still apply. CLI:
 * `--provider <X> --model <Y>` (both required together).
 *
 * Wave B #5: `cli-eval-model-override`.
 */
provider_override: ProviderOverride | null,
/**
 * Optional per-run subset of the strategy's `asset_universe`. When set,
 * only the listed assets are traded in this run (backtest only — paper
 * mode ignores this field today). Every entry must be present in the
 * strategy's `asset_universe`; validation is performed inside
 * `build_backtest_executor` via `active_assets`.
 *
 * CLI: `--assets ETH,SOL` (comma-separated). `None` (default) trades
 * the full universe as declared in the strategy manifest.
 */
assets_subset: Array<string> | null,
/**
 * When true, finalizing a successful run fires the rule-based review
 * agent and stores chart annotations on `eval_reviews.annotations_json`.
 * Default false: auto-review is opt-in per run.
 */
auto_fire_review: boolean,
/**
 * Optional display override for the review model requested by the
 * launcher. The current wave persists this for audit/UI; manual review
 * engine routing continues to use the selected agent profile.
 */
review_model: ReviewModel | null,
/**
 * Maximum annotations the review contract should emit. Stored on the
 * run so UI/CLI launches round-trip their annotation budget.
 */
max_annotations_per_review: number | null, };
