// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the harness drives a multi-asset universe per bar.
 */
export type ExecutionMode = "per_asset" | "portfolio" | { "custom": string };
