// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FactoryResetReport = { xvn_home: string, 
/**
 * Path of the audit log we mirrored to so the operator can find it
 * after the wipe.
 */
audit_log_path: string, };
