// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance tag describing which source provided the fee/slippage for a fill.
 *
 * Populated on `FillProvenance` so the trace surface can distinguish how
 * cost was resolved at each bar.
 */
export type FeeSource = "default" | "scenario_override" | "per_asset_override" | "per_bar_array";
