// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of the `fee_bps` applied to a fill.
 */
export type FeeSource = "default" | "scenario_override" | "per_asset_override" | "per_bar_array";
