// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind";

/**
 * One file's body, returned by `read`. Truncated at 256 KB with
 * `truncated: true` set on the response so the wizard can detect partial
 * reads and either ask for a smaller scope or call the (future) chunked
 * reader.
 */
export type FileContent = { rel_path: string, kind: FileKind, 
/**
 * File body, decoded as UTF-8 with lossy replacement for invalid
 * sequences (PDFs etc. are still returned — agents can decide whether
 * to ignore the binary blob or call a future summary extractor).
 */
content: string, 
/**
 * `true` when the file is larger than the 256 KB cap and `content`
 * has been truncated to the cap.
 */
truncated: boolean, };
