// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File-kind classification driven purely by extension. Anything not in
 * the allowlist falls into `Other` — the wizard tool surfaces it as an
 * opaque entry the agent can still see in the `list` result.
 */
export type FileKind = "markdown" | "json" | "csv" | "pdf" | "text" | "other";
