// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitOrderFill } from "./LimitOrderFill";
import type { MarketOrderFill } from "./MarketOrderFill";
import type { VolumeConstraint } from "./VolumeConstraint";

export type FillModel = { market_order_fill: MarketOrderFill, limit_order_fill: LimitOrderFill, partial_fills: boolean, volume_constraints: VolumeConstraint | null, };
