// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggressorSide } from "./AggressorSide";
import type { FeeSource } from "./FeeSource";
import type { FillBranch } from "./FillBranch";

/**
 * Per-fill provenance record — appended to the fill columns in
 * `decisions.jsonl` so downstream tracks have a stable slot to write into.
 *
 * All fields default to zero-values / `None` so old runs (schema_version="1")
 * deserialize cleanly.
 */
export type FillTrace = { 
/**
 * Intra-bar fill branch taken. `None` when not populated (pre-intra-bar
 * ordering) or for non-fill decisions (hold/flat-no-position).
 */
fill_branch: FillBranch | null, 
/**
 * Slippage applied in basis points.
 */
slip_bps_applied: number, 
/**
 * Half-spread applied in basis points.
 */
spread_bps_applied: number, 
/**
 * Fee applied in basis points.
 */
fee_bps_applied: number, 
/**
 * Source of the fee rate.
 */
fee_source: FeeSource, 
/**
 * Fill quantity as a fraction of the bar's traded volume.
 * `None` when volume-share slippage is not modelled.
 */
volume_share: number | null, 
/**
 * True when the fill was capped by the venue's volume-share limit.
 */
volume_cap_bound: boolean, 
/**
 * Aggressor side for this fill. `None` when not classified (pre-intra-bar
 * ordering track).
 */
aggressor_side: AggressorSide | null, };
