// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which intra-bar path was taken for a simulated fill.
 *
 * Foundation lands the type as `Option<FillBranch>` defaulting `None`;
 * `eval-intra-bar-fill-ordering` populates the values in a later V2E track.
 * The enum is `#[non_exhaustive]` so downstream tracks can add variants
 * without breaking existing match arms.
 */
export type FillBranch = "gap_past" | "ohlc_high_first" | "ohlc_low_first" | "next_open_only";
