// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterId } from "./FilterId";

/**
 * Aggregate rollup for a single filter across one eval run.
 *
 * Built from the `FilterEventV1` stream after the run completes and
 * embedded in both `RunSummary` and detailed run export payloads.
 */
export type FilterSummary = { filter_id: FilterId, bars_scanned: number, wakeups: number, suppressed_in_position: number, suppressed_daily_cap: number, suppressed_cooldown: number, llm_calls_saved: number, estimated_tokens_saved: number, };
