// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterId } from "./FilterId";
import type { SuppressedReason } from "./SuppressedReason";

/**
 * One per-bar emission for a filter evaluated in FilterGated mode.
 *
 * Emitted to the same `events.jsonl` channel that carries the V2D
 * `memory_*` events and the V2E trace events. Read by the run export,
 * the run-detail panel (Stage 4), and the golden regression fixtures
 * (Stage 5).
 */
export type FilterEventV1 = {
/**
 * Schema version. Always `1` for v1; bumped when the shape
 * changes incompatibly.
 */
schema_version: number, bar_timestamp: string, filter_id: FilterId,
/**
 * True iff the runtime returned `Active { transition: Trip }` — the
 * bar an LLM dispatch fired. `false` for Inactive / Warming / Hold
 * and for all suppressed outcomes.
 */
triggered: boolean,
/**
 * Set when a would-have-triggered bar was suppressed by a runtime
 * gate. `None` means no suppression was active — either a real
 * trip or a no-op bar.
 */
suppressed_reason: SuppressedReason | null,
/**
 * Indices (into `ConditionTree::conditions()`) of leaves that
 * evaluated `true` on this bar. Empty during warmup.
 */
conditions_passed: Array<number>,
/**
 * Indices of leaves that evaluated `false`. Empty during warmup.
 */
conditions_failed: Array<number>,
/**
 * Sparse map of `IndicatorRef.to_string()` → bar value
 * (e.g. `"ema_20" → 42_133.12`). Empty during warmup. Includes
 * only the indicators referenced by this filter.
 */
indicator_snapshot: { [key: string]: number }, };
