// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndicatorRef } from "./IndicatorRef";

/**
 * Optional author-facing metadata attached to a filter trip. This does
 * not change whether a filter fires; it tells downstream agent surfaces
 * why the gate fired and which compact indicator values should be
 * surfaced with the trigger.
 */
export type FilterFire = { reason: string, priority: number, tags: Array<string>, context: Array<IndicatorRef>, };
