// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type Finding = { id: string, run_id: string, 
/**
 * Open enum: `regime_fit_mismatch`, `drawdown_concentration`,
 * `overtrading`, `underperformance`, `risk_violation`, `win_rate_anomaly`,
 * `tail_risk`, or any LLM-proposed new kind. Validation belongs to
 * downstream consumers.
 */
kind: string, severity: Severity, summary: string, 
/**
 * LLM-extracted evidence blob — open-ended JSON. Typed as `unknown` on
 * the wire so consumers narrow with a runtime guard if they need fields.
 */
evidence: unknown, extracted_at: string, schema_version: string, };
