// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlywheelStatusDto = { namespace: string, observations: number, active_patterns: number, staged_patterns: number, forgotten_patterns: number, autooptimizer_runs: number, latest_autooptimizer_run_id: string | null, latest_autooptimizer_created_at: string | null, };
