// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlywheelStatusDto = { namespace: string, observations: bigint, active_patterns: bigint, staged_patterns: bigint, forgotten_patterns: bigint, autooptimizer_runs: bigint, latest_autooptimizer_run_id: string | null, latest_autooptimizer_created_at: string | null, };
