// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlywheelVelocityRequest = { 
/**
 * Exact namespace, e.g. `global` or `agent:<id>`.
 */
namespace: string | null, 
/**
 * Convenience shorthand for `namespace = agent:<id>`.
 */
agent: string | null, 
/**
 * Lookback window in days. Defaults to 7.
 */
days: bigint | null, };
