// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlywheelVelocityDto = { namespace: string, days: bigint, since: string, observations_captured: bigint, patterns_promoted: bigint, patterns_demoted: bigint, autooptimizer_runs: bigint, optimized_child_agents: bigint, average_lineage_depth: number, latest_activity_at: string | null, };
