// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlywheelVelocityDto = { namespace: string, days: number, since: string, observations_captured: number, patterns_promoted: number, patterns_demoted: number, autooptimizer_runs: number, optimized_child_agents: number, average_lineage_depth: number, latest_activity_at: string | null, };
