// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlywheelLineageItemDto } from "./FlywheelLineageItemDto";

export type FlywheelLineageDto = { namespace: string, items: Array<FlywheelLineageItemDto>, total: bigint, };
