// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A loaded or freshly-saved focus document: its resolved on-disk path, the
 * UTF-8 content, and the content-addressed hash used to detect drift and to
 * stamp [`FocusEvent`](xvision_observability::FocusEvent)s.
 */
export type FocusDoc = { 
/**
 * Absolute path to the focus file (`…/scopes/<kind>/<id>/focus.md`).
 */
path: string, 
/**
 * Full UTF-8 content of the focus file.
 */
content: string, 
/**
 * Lowercase hex `sha256(content)`. Stable for identical content; changes
 * on any edit. Mirrors the `content_hash` carried on `FocusEvent`.
 */
content_hash: string, };
