// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind";

/**
 * One enumerated entry under `$XVN_HOME/strategies/`. `rel_path` is the
 * path relative to `folder_root()` using forward slashes, so the wizard
 * can quote it verbatim when calling `read_strategies_file`.
 */
export type FolderEntry = { 
/**
 * Path relative to `folder_root()`, forward-slash separated.
 */
rel_path: string, kind: FileKind, size_bytes: bigint, 
/**
 * RFC3339 UTC timestamp of the file's last-modified mtime. Empty
 * string when the mtime is unavailable on the host filesystem.
 */
modified_at: string, };
