// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgetResponse = { 
/**
 * Number of rows affected by the call. When grace > 0 these are
 * soft-deleted (still in-table with `forgotten_at` set);
 * when grace == 0 they are hard-deleted.
 */
deleted: bigint, 
/**
 * RFC3339 timestamp until which `undo-forget` will restore the
 * rows soft-deleted by this call. `None` when grace == 0 (the
 * rows are gone immediately and there is nothing to restore).
 */
restorable_until: string | null, 
/**
 * Resolved grace window in days (0 means immediate hard-delete).
 */
grace_days: number, };
