// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";
import type { Probe } from "./Probe";

export type HealthReport = { status: HealthStatus, probes: Array<Probe>, };
