// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HoldMarker = { time: number, price: number, conviction: number | null, decision_index: number, };
