// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the [`list_ideas`] response. Shaped for the wizard agent's
 * consumption — short, quotable, and points back at the original file
 * via `source_rel_path` so the agent can call `read_strategies_file`
 * to fetch the full template.
 */
export type IdeaSummary = { 
/**
 * Stable identifier — uses the template's `name` field
 * (e.g. `ema_pullback_bounce`). Unique per category.
 */
id: string, 
/**
 * Category, normalized to lowercase + hyphenated (e.g. `ema`,
 * `rsi-volume`, `fibonacci`). Stable across renames of the
 * underlying folder (see [`normalize_category`]).
 */
category: string, 
/**
 * Indicators referenced by the template. Derived from the
 * `required_tools` array plus any `IndicatorPanel.<name>` /
 * `OnchainPanel.<name>` references in the `inputs` section.
 * Lowercased + de-duplicated; order is the order discovered.
 */
indicators: Array<string>, 
/**
 * Display name. Falls back to `name` if `display_name` is missing.
 */
name: string, 
/**
 * Short summary. Falls back through `plain_summary`,
 * `sections.thesis`, then truncated `sections.decision_rule`.
 * Whitespace-normalized and clipped to ~280 chars.
 */
summary: string, 
/**
 * Path relative to `folder_root()` (forward-slash separated) that
 * the agent can pass to `read_strategies_file` to fetch the full
 * template.
 */
source_rel_path: string, };
