// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter passed to [`list_ideas`]. All fields optional; an empty filter
 * returns the first [`DEFAULT_LIMIT`] entries.
 */
export type IdeaFilter = { 
/**
 * Optional category (subfolder) filter. Case-insensitive; see
 * module docs for the normalization rules.
 */
category: string | null, 
/**
 * Optional indicator filter. Case-insensitive substring match
 * against the derived `indicators` vec on each idea.
 */
indicator: string | null, 
/**
 * Optional cap on the number of results. Defaults to
 * [`DEFAULT_LIMIT`], clamped to [`MAX_LIMIT`]. Non-positive values
 * fall back to the default.
 */
limit: number | null, };
