// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletStatus } from "./WalletStatus";

export type IdentityReport = { 
/**
 * Was the build compiled with the `xvision-identity` member? In default
 * `cargo build` (no `--workspace`) this is false; in
 * `cargo build --workspace` or the `:identity` docker tag, true.
 */
feature_compiled_in: boolean, 
/**
 * Wallet config snapshot (env-var presence; values never returned).
 */
wallet: WalletStatus, 
/**
 * Note explaining the v1 stance (read-only, no minting).
 */
note: string, };
