// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletStatus } from "./WalletStatus";

export type IdentityReport = {
/**
 * Was the build compiled with the `xvision-identity` member? In default
 * `cargo build` (no `--workspace`) this is false; in
 * `cargo build --workspace` or the `:identity` docker tag, true.
 */
feature_compiled_in: boolean,
/**
 * Wallet config snapshot (env-var presence; values never returned).
 */
wallet: WalletStatus,
/**
 * Note explaining the v1 stance (read-only, no minting).
 */
note: string,
/**
 * NFT token id for the platform agent on the Mantle registry.
 * None when XVN_PLATFORM_AGENT_TOKEN_ID is absent or unparseable.
 */
agent_token_id: bigint | null,
/**
 * On-chain address of the identity registry contract.
 * None when XVN_IDENTITY_REGISTRY is absent.
 */
identity_registry: string | null,
/**
 * Tx hash of the most recent chain attestation recorded in the local store.
 * None when no attestation has been posted yet.
 */
last_attestation_tx: string | null,
/**
 * Base URL for Mantlescan block explorer links.
 */
mantlescan_base_url: string, };
