// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndicatorName } from "./IndicatorName";

/**
 * A reference to an indicator in a `Condition`. The DSL wire form is a
 * single string (`"ema_20"`, `"close"`) — see the module-level docs.
 */
export type IndicatorRef = { name: IndicatorName, 
/**
 * `None` only when `name == Close`. Validator enforces this.
 */
period: number | null, 
/**
 * Bar-relative offset for v1.5 plugins (positive = future). v1 has
 * no DSL syntax for this; the validator rejects any `Some(n)` with
 * `n > 0` (`E_FILTER_FUTURE_LEAK`). Skipped on serialize when `None`
 * so DSL output stays clean.
 */
bar_offset?: number, };
