// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The closed v1 indicator catalog. New entries (vwap, bbands, macd) land
 * in v1.5+ alongside the SlotRuntime split.
 */
export type IndicatorName = "ema" | "sma" | "rsi" | "atr" | "atr_pct" | "close";
