// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence payload for the `inference_cost_dominates_return` finding kind
 * (V2E item 25). Persisted as the `evidence` JSON blob on the `Finding`.
 *
 * `produced_by_check = "metrics:cost_dominance"`.
 * `evidence_cycle_ids` is empty — this is a per-run aggregate.
 */
export type InferenceCostDominatesReturnPayload = { 
/**
 * `|inference_cost_quote_total| / |gross_return_quote|`. Values > threshold
 * triggered the finding.
 */
ratio: number, 
/**
 * The configured threshold k (default 0.5).
 */
threshold: number, 
/**
 * Gross trading return in USD (capital × gross_return_pct / 100).
 */
gross_return_quote: number, 
/**
 * Total LLM inference cost for this run in USD.
 */
inference_cost_quote_total: number, };
