// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence payload for the `inference_cost_dominates_return` finding.
 * Emitted when |cost_total| > threshold × |gross_return_quote|.
 */
export type InferenceCostDominatesReturnPayload = { ratio: number, threshold: number, gross_return_quote: number, inference_cost_quote_total: number, };
