// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InlineChartSource = { label: string, href: string | null, run_id: string | null, strategy_id: string | null, };
