// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineTone } from "./InlineTone";

export type InlineMetric = { label: string, value: string, unit: string | null, tone: InlineTone | null, };
