// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineAction } from "./InlineAction";
import type { InlineChartKind } from "./InlineChartKind";
import type { InlineChartSeries } from "./InlineChartSeries";
import type { InlineChartSource } from "./InlineChartSource";
import type { InlineMetric } from "./InlineMetric";

export type InlineChartPayload = { chart_id: string, kind: InlineChartKind, title: string, subtitle: string | null, primary_metric: InlineMetric | null, metrics: Array<InlineMetric>, series: Array<InlineChartSeries>, source: InlineChartSource | null, actions: Array<InlineAction>, a11y_summary: string, downsampled: boolean, };
