// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlinePoint } from "./InlinePoint";
import type { InlineTone } from "./InlineTone";

export type InlineChartSeries = { id: string, label: string, tone: InlineTone | null, points: Array<InlinePoint>, };
