// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the eval executor sanitizes the seed JSON before handing it to
 * the trader LLM. Persisted as the `inputs_policy` column on
 * `agent_slots` (migration 020). See harness audit F-6
 * (`team/intake/2026-05-19-eval-traces-end-to-end-audit.md`).
 *
 * - `Raw` — today's behavior. `decision_index` lives on the top-level
 *   seed; every `bar_history` entry carries `timestamp`. This is the
 *   migration default, so existing rows are unaffected. The
 *   regression-guard unit test in `eval::executor::paper` pins this
 *   shape byte-for-byte.
 * - `Causal` — drop `decision_index` from the top-level seed and
 *   replace each `bar_history` entry's `timestamp` field with
 *   `bar_index` (0 = oldest visible bar in the `bar_history` slice).
 *   The current bar still carries its OHLCV — only the wall-clock
 *   label is hidden, which matches the v4 causal prompts.
 * - `Oracle` — behaves identically to `Raw` at runtime. The tag
 *   exists so downstream consumers can mark a slot as deliberately
 *   oracle-style (the two seeded oracle agents are documented in the
 *   F-6 audit). It's distinct from `Raw` so the UI / cohort tagging
 *   can tell "left at default" apart from "deliberately full
 *   visibility."
 */
export type InputsPolicy = "raw" | "causal" | "oracle";
