// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire view of a dropped/invalid provider row (see [`ProvidersReport::invalid`]).
 */
export type InvalidProviderRow = { 
/**
 * The (invalid) name as written in the config — also the key used to
 * remove the row via `DELETE /providers/:name`.
 */
name: string, 
/**
 * Human-readable reason the row was rejected.
 */
reason: string, };
