// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListAgentsRequest = { include_archived: boolean, q: string | null, limit: bigint | null, };
