// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListMemoryRequest = { 
/**
 * `"observation"` or `"pattern"`. `None` returns both tiers (used
 * by the per-agent Memory tab to populate both sub-tabs in one
 * fetch — the UI partitions client-side).
 */
tier: string | null, 
/**
 * Exact namespace match — e.g. `"global"` or `"agent:<id>"`.
 */
namespace: string | null, 
/**
 * Convenience filter — when set, narrows to `namespace =
 * "agent:<agent>"`. Mutually exclusive with `namespace`; passing
 * both is a validation error.
 */
agent: string | null, 
/**
 * Observation provenance filters. Both `None` returns all.
 */
scenario_id: string | null, run_id: string | null, limit: bigint | null, offset: bigint | null, 
/**
 * When `Some(true)`, soft-deleted rows are included. Default is
 * to skip rows with non-null `forgotten_at`.
 */
include_forgotten: boolean | null, };
