// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListAgentsRequest = { include_archived: boolean, q: string | null, limit: bigint | null, 
/**
 * Optional row offset for paged listings. The dashboard's list
 * route always sets `(limit, offset)`; CLI/MCP callers that want
 * the full library leave both unset.
 */
offset: bigint | null, 
/**
 * Scope visibility filter. `None` (default) and `Some("")` map to
 * `ScopeFilter::Workspace` — only workspace agents (rows where
 * `scope_strategy_id IS NULL`). `Some("all")` opts out of the
 * filter entirely (diagnostic). Any other value is interpreted as
 * a strategy id and merges that strategy's scoped agents with the
 * workspace set. Phase 3 of `agent-firing-filter`, migration 036.
 */
scope: string | null, };
