// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioSource } from "./ScenarioSource";

/**
 * Filter for `list`. All fields are AND-composed; `Default` means "no
 * filter on any dimension" (and excludes archived rows).
 */
export type ListScenariosFilter = { source: ScenarioSource | null, tags: Array<string>, include_archived: boolean, parent_scenario_id: string | null, 
/**
 * Optional page-size cap. The dashboard list endpoint sets both
 * `limit` and `offset`; CLI / MCP callers leave them unset.
 */
limit: number | null, offset: number | null, };
