// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { SafetyLimits } from "./SafetyLimits";
import type { StopPolicy } from "./StopPolicy";
import type { VenueLabel } from "./VenueLabel";

/**
 * Launch envelope for a Live run. Persisted as
 * `eval_runs.live_config_json` (Phase B migration).
 *
 * `strategy_id` references the strategy artifact that drives the run.
 * `assets` is `Vec` for forward-compat with multi-asset Live launches
 * (see `docs/superpowers/plans/2026-05-21-multi-asset-alpaca-unlock.md`);
 * v1 hard-walls it to `len() == 1`.
 *
 * `broker_creds_ref` resolves to a configured broker-credentials row;
 * the engine never stores the secret material itself in `LiveConfig`.
 */
export type LiveConfig = { strategy_id: string, assets: Array<AssetRef>, 
/**
 * Initial trading capital. Same shape as `Scenario.capital`; inlined
 * in the ts-rs export because `xvision_core::Capital` is not a ts-rs
 * type (mirrors the existing override on `Scenario`).
 */
capital: { initial: number, currency: string }, broker_creds_ref: string, stop_policy: StopPolicy, 
/**
 * Coarse safety label for the venue. v1 rejects [`VenueLabel::Live`]
 * at validation; once the per-strategy verdict + kill-switch hardening
 * lands, this opens up.
 */
venue_label: VenueLabel, 
/**
 * Optional override for the historical warm-up window the strategy
 * gets before live bars start flowing. `None` falls through to the
 * strategy's declared warm-up.
 */
warmup_bars: number | null, 
/**
 * Per-run notional / order-count / leverage / drawdown limits. Same
 * shape as `Scenario.safety_limits`.
 */
safety_limits: SafetyLimits | null, display_name: string, description: string | null, tags: Array<string>, notes: string | null, };
