// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveRunState = { run_id: string, strategy_id: string | null, strategy_name: string | null, deployed_capital_usd: number, equity_usd: number | null, unrealized_pnl_usd: number | null, realized_pnl_usd: number | null, realized_today_usd: number | null, daily_loss_remaining_usd: number | null, drawdown_pct: number | null, peak_equity_usd: number | null, risk_veto_count: number, last_decision_at: string | null, updated_at: string, 
/**
 * Daily-loss budget in USD = kill_pct × initial capital. `None` when
 * the strategy has no kill percentage configured (kill_pct == 0.0).
 * Unlocks the strip's buffer %-gradient (remaining / budget).
 */
daily_loss_budget_usd: number | null, 
/**
 * Wall-clock deadline (RFC-3339) = started_at + time_limit_secs. `None`
 * when the stop policy is bar- or decision-bounded (no wall-clock ETA).
 * Unlocks awm's ETA display.
 */
stop_at: string | null, };
