// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable validation errors for a `LiveConfig`. Each variant carries
 * enough structured context for the frontend to render a targeted
 * inline error next to the offending field, and `field_path()` returns
 * the JSON pointer the UI uses to scroll/focus to the relevant input.
 *
 * `BrokerCredsUnreachable` is reserved for the launch endpoint to
 * raise after its reachability probe — it is **never** returned by
 * [`LiveConfig::validate`] (which is a pure / non-IO check).
 */
export type LiveConfigValidationError = { "code": "display_name_empty" } | { "code": "strategy_id_empty" } | { "code": "broker_creds_empty" } | { "code": "asset_count", "detail": { actual: number, } } | { "code": "asset_not_whitelisted", "detail": { index: number, symbol: string, } } | { "code": "stop_policy_empty" } | { "code": "stop_policy_limit_not_positive", "detail": { field: string, } } | { "code": "stop_policy_time_limit_too_long", "detail": { secs: bigint, max: bigint, } } | { "code": "venue_label_live_rejected" } | { "code": "capital_not_positive", "detail": { initial: number, } } | { "code": "broker_creds_unreachable", "detail": { reason: string, } };
