// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { SafetyLimits } from "./SafetyLimits";
import type { StopPolicy } from "./StopPolicy";
import type { VenueLabel } from "./VenueLabel";

/**
 * Launch envelope for a Live run. Persisted as
 * `eval_runs.live_config_json` (Phase B migration).
 *
 * **Current live scope: Alpaca paper trading only.** Live mode sends
 * orders to `https://paper-api.alpaca.markets` — real market data,
 * paper (simulated) money. Real-money venues (`VenueLabel::Live`) are
 * rejected at validation until the per-strategy verdict + kill-switch
 * hardening lands.
 *
 * `strategy_id` references the strategy artifact that drives the run.
 * `assets` is a non-empty list of whitelisted assets; each is fanned out
 * into its own `LiveStream` and merged in the executor (§4 L2 multi-asset
 * live fanout, see
 * `docs/superpowers/plans/2026-05-25-cline-live-followups.md` and the
 * invariants in
 * `docs/superpowers/notes/2026-05-25-live-multi-asset-invariants.md`). The
 * earlier single-asset wall (`len() == 1`) has been lifted.
 *
 * `broker_creds_ref` selects WHICH stored credential set to load
 * (e.g. `"alpaca"` → the Alpaca credentials row). It is a lookup key,
 * not a venue/environment selector — venue selection is a separate
 * future plan. The engine never stores secret material in `LiveConfig`.
 */
export type LiveConfig = { strategy_id: string, assets: Array<AssetRef>, 
/**
 * Initial trading capital. Same shape as `Scenario.capital`; inlined
 * in the ts-rs export because `xvision_core::Capital` is not a ts-rs
 * type (mirrors the existing override on `Scenario`).
 */
capital: { initial: number, currency: string }, 
/**
 * Selects WHICH stored credential set to use (e.g. `"alpaca"` → the
 * Alpaca credentials row under Settings → Brokers). This is a lookup
 * key, **not** a venue/environment selector — venue and environment
 * selection is a separate future plan. Current live scope accepts only
 * `"alpaca"` (Alpaca paper trading).
 */
broker_creds_ref: string, stop_policy: StopPolicy, 
/**
 * Coarse safety label for the venue. v1 rejects [`VenueLabel::Live`]
 * at validation; once the per-strategy verdict + kill-switch hardening
 * lands, this opens up.
 */
venue_label: VenueLabel, 
/**
 * Optional override for the historical warm-up window the strategy
 * gets before live bars start flowing. `None` falls through to the
 * strategy's declared warm-up.
 */
warmup_bars: number | null, 
/**
 * Per-run notional / order-count / leverage / drawdown limits. Same
 * shape as `Scenario.safety_limits`.
 */
safety_limits: SafetyLimits | null, display_name: string, description: string | null, tags: Array<string>, notes: string | null, };
