// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire type for the live-deployments list/detail API.
 * Represents one paper or testnet live run with its current capital-risk snapshot.
 * `venue_label` is always "paper" or "testnet" — 'live' is excluded by the query.
 */
export type LiveDeploymentSummary = { deployment_id: string, strategy_id: string | null, strategy_name: string | null, 
/**
 * "paper" | "testnet" — 'live' excluded by the query filter.
 */
venue_label: string, 
/**
 * queued | running | completed | failed | cancelled
 */
status: string, paused: boolean, started_at: string, last_decision_at: string | null, deployed_capital_usd: number | null, equity_usd: number | null, realized_pnl_usd: number | null, unrealized_pnl_usd: number | null, realized_today_usd: number | null, drawdown_pct: number | null, daily_loss_limit_remaining_usd: number | null, risk_veto_count: number, daily_loss_budget_usd: number | null, stop_at: string | null, };
