// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { IndicatorPoint } from "./IndicatorPoint";

export type MacdSeries = { line: Array<IndicatorPoint>, signal: Array<IndicatorPoint>, histogram: Array<IndicatorPoint>, };
