// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `compare_runs` when the runs' `manifest_canonical` values
 * disagree and `allow_manifest_mismatch` is `false`.
 */
export type ManifestMismatch = { run_a: string, run_b: string, 
/**
 * Human-readable list of differing manifest fields. Derived from the
 * `bars_manifest` JSON blobs; empty when blobs aren't present (i.e. the
 * only signal is the hash mismatch).
 */
diff_fields: Array<string>, };
