// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketplaceProvenance = {
/**
 * On-chain listing id (`== license_token_id` by the surface-spec
 * invariant) the buyer purchased.
 */
listing_id: string,
/**
 * Listing tier: `"open"` (plaintext manifest) or `"sealed"`
 * (Lit-encrypted manifest).
 */
tier: string,
/**
 * Seller handle / address from the listing (the strategy author).
 */
creator: string,
/**
 * Price paid in whole USDC. `0.0` for a free / open-tier listing.
 */
price_usdc: number,
/**
 * ERC-1155 license token id minted to the buyer — equals `listing_id`.
 */
license_token_id: string,
/**
 * Network label, e.g. `"mantle-sepolia"` / `"mantle"`. Best-known label
 * even when the chain env is unset (so the strip still says where it
 * came from).
 */
network: string,
/**
 * Direct block-explorer link to the owned license token. `None` when the
 * chain is unconfigured (no license-token address) or the network has no
 * known explorer — the UI then renders a muted, non-link label.
 */
explorer_url?: string, };
