// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On-chain marketplace provenance for a strategy acquired from the
 * marketplace (issue #12 / QA #8): creator, price paid, license NFT, and a
 * "View on Explorer" link to the owned license token.
 *
 * Stored in a SIDECAR JSON file next to the strategy (`{id}.marketplace.json`),
 * NOT on the `Strategy` struct — provenance is import metadata, not part of the
 * immutable strategy artifact, and a `Strategy` field would force every one of
 * the ~89 `Strategy { .. }` literals across the workspace to be edited. The
 * sidecar keeps the change to the import + read paths only. Absent sidecar =
 * hand-authored / optimizer-minted strategy (no strip shown).
 */
export type MarketplaceProvenance = { 
/**
 * On-chain listing id the buyer purchased (== `license_token_id`).
 */
listing_id: string, 
/**
 * Listing tier: `"open"` (plaintext manifest) or `"sealed"` (Lit-encrypted).
 */
tier: string, 
/**
 * Seller handle / address from the listing (the strategy author).
 */
creator: string, 
/**
 * Price paid in whole USDC. `0.0` for a free / open-tier listing.
 */
price_usdc: number, 
/**
 * ERC-1155 license token id minted to the buyer — equals `listing_id`.
 */
license_token_id: string, 
/**
 * Network label, e.g. `"mantle-sepolia"` / `"mantle"`. Best-known label
 * even when the chain env is unset.
 */
network: string, 
/**
 * Direct block-explorer link to the owned license token. `None` when the
 * chain is unconfigured / has no known explorer — the UI renders a muted,
 * non-link label.
 */
explorer_url?: string, };
