// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-namespace live-observation count for the status report.
 */
export type MemoryNamespaceStatus = { namespace: string, live_observations: bigint, };
