// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryDemoOptimizeRequest = { target_agent_id: string, 
/**
 * Slot name to patch. Defaults to the first slot.
 */
slot: string | null, 
/**
 * Exact memory namespace, e.g. `global` or `agent:<id>`.
 */
namespace: string | null, 
/**
 * Convenience shorthand for `namespace = agent:<id>`.
 */
memory_agent: string | null, scenario_id: string | null, run_id: string | null, 
/**
 * Demo source selector. Supported values:
 * `frozen-snapshot`, `fresh-recorder`, and `manual-csv`.
 */
demo_source: string | null, 
/**
 * Train/dev/holdout split, e.g. `70/15/15`.
 */
holdout_split: string | null, 
/**
 * Verbatim cohort selector recorded for reproducibility. Filtering
 * is currently represented by namespace/scenario/run fields.
 */
cohort_query: string | null, 
/**
 * Observation ids supplied by CLI when `demo_source=manual-csv`.
 */
manual_observation_ids: Array<string> | null, 
/**
 * Optional Pattern ids to inject as semantic priors. They are
 * recorded in `pattern_optimizations` with role `prior`.
 */
prior_pattern_ids: Array<string> | null, 
/**
 * Opt-in selector for Patterns recently recalled by live/eval
 * cycles in this namespace. Manual prior_pattern_ids are kept
 * first; auto priors are appended deterministically.
 */
auto_prior_patterns: boolean, prior_pattern_limit: bigint | null, limit: bigint | null, max_demo_chars: number | null, 
/**
 * When true, mint a child Agent. When false, return a dry-run
 * preview with the same selected demo ids.
 */
apply: boolean, child_name: string | null, };
