// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryNamespaceDto = { namespace: string, live_total: bigint, observations: bigint, active_patterns: bigint, staged_patterns: bigint, forgotten: bigint, latest_created_at: string | null, };
