// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryDemoObservationDto = { id: string, run_id: string, scenario_id: string, cycle_idx: bigint, source_window_end: string, };
