// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire representation of a memory item. Mirrors `MemoryItem` but
 * flattens `chrono::DateTime` to RFC3339 strings and drops the raw
 * embedding blob (operators don't need to see the vector).
 */
export type MemoryItemDto = { id: string, namespace: string, 
/**
 * `"observation"` or `"pattern"`.
 */
tier: string, text: string, 
/**
 * RFC3339 timestamp.
 */
created_at: string, run_id: string | null, scenario_id: string | null, cycle_idx: bigint | null, 
/**
 * RFC3339 date; `None` on Observations and on operator-attested
 * Patterns where the operator wants global applicability.
 */
training_window_end: string | null, 
/**
 * RFC3339 timestamp of when the row was soft-deleted via
 * `forget`. `None` on live rows.
 */
forgotten_at: string | null, };
