// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryItemDto } from "./MemoryItemDto";

export type MemoryListResponse = { items: Array<MemoryItemDto>, 
/**
 * Total matching rows before LIMIT/OFFSET.
 */
total: bigint, };
