// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report DTO returned by both `get` and `set`. `embedder` is the flat
 * config string (`off`/`local`/`auto`/<provider>).
 */
export type MemoryReport = { embedder: string, chat_enabled: boolean, optimizer_enabled: boolean, 
/**
 * True when the persisted config file exists. False → defaults are in
 * force; the UI renders "Default" vs "Custom".
 */
persisted: boolean, };
