// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report DTO returned by both `get` and `set`. `embedder` is the flat
 * config string (`off`/`local`/`auto`/<provider>).
 */
export type MemoryReport = { embedder: string, chat_enabled: boolean, optimizer_enabled: boolean, 
/**
 * The persisted embedding model id, or `null` when none is set (the
 * resolver default applies). The card renders this as the embedding-
 * model picker value; empty/clear sends `""` which stores `None`.
 */
embedder_model: string | null, 
/**
 * Base URL for the `"custom"` embedder source (no-auth OpenAI-compatible
 * `/v1` endpoint), or `null` when none is set. The card renders this in
 * the custom base-URL input, shown only when the source is `custom`.
 */
embedder_base_url: string | null, 
/**
 * True when the persisted config file exists. False → defaults are in
 * force; the UI renders "Default" vs "Custom".
 */
persisted: boolean, };
