// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryNamespaceDto = { namespace: string, live_total: number, observations: number, active_patterns: number, staged_patterns: number, forgotten: number, latest_created_at: string | null, };
