// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryNamespaceStatus } from "./MemoryNamespaceStatus";

/**
 * Operator health snapshot for the Cortex memory layer. Consumed by
 * `xvn memory status` and folded into `xvn doctor` so both surfaces
 * report the same store path, embedder presence/source, grace window,
 * and per-namespace live-observation counts from a single source.
 */
export type MemoryStatus = { 
/**
 * Resolved memory DB path (`$XVN_MEMORY_DB` chain).
 */
store_path: string, 
/**
 * Whether the store's parent dir is writable by this process.
 */
writable: boolean, 
/**
 * True when an embedder source resolved (recall/record can embed).
 */
embedder_present: boolean, 
/**
 * The embedder id (`local:hash-v1`, `openaicompat:<model>` e.g.
 * `openaicompat:nomic-embed-text`) when present.
 */
embedder_id: string | null, 
/**
 * Which resolution branch won (`local`, `openai-compat`).
 */
embedder_source: string | null, 
/**
 * The soft-delete grace window in days (`XVN_MEMORY_FORGET_GRACE_DAYS`).
 */
grace_days: number, 
/**
 * Per-namespace live-observation counts.
 */
namespaces: Array<MemoryNamespaceStatus>, };
