// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaselinesReport } from "./BaselinesReport";

/**
 * Headline metrics the eval engine computes after a run completes.
 * Persisted as `metrics_json` on the `eval_runs` row by `RunStore::finalize`.
 *
 * The `baselines` field is optional and backward-compatible: old rows that
 * were finalized before baselines were introduced deserialize with
 * `baselines: None`. New runs always populate it.
 *
 * Net-of-inference-cost fields (V2E item 25):
 * - `gross_return_pct` is a method alias for `total_return_pct` (the stored
 *   field name). `total_return_pct` continues to serialize under that name
 *   for one release (backward compat); V2F will rename it on the wire.
 * - `inference_cost_quote_total` — sum of all per-decision inference cost
 *   quotes (USD). `None` when pricing data is unavailable for the model.
 * - `net_return_pct` — `gross_return_pct − (inference_cost_quote_total /
 *   capital_initial × 100)`. `None` when `inference_cost_quote_total` is
 *   unavailable.
 */
export type MetricsSummary = {
/**
 * Gross trading return as a percentage of starting capital.
 * Deprecated wire name: `total_return_pct` (kept for one release).
 * Use `MetricsSummary::gross_return_pct()` as the forward-looking accessor.
 * Deserialization accepts `gross_return_pct` as an alias so JSON written
 * by future code that uses the new name can still round-trip.
 */
total_return_pct: number, sharpe: number, max_drawdown_pct: number,
/**
 * Fraction of CLOSED ROUND-TRIPS that realized positive PnL
 * (`wins / realized_count`). A round-trip is one position open→flat
 * cycle, closed by the trader (`flat`/flip) or a deterministic SL/TP
 * exit. `0.0` when no round-trip closed.
 */
win_rate: number,
/**
 * Count of FILL LEGS that crossed the book — opens, closes, SL/TP forced
 * exits, and partial-TP1 slices each count one. An open+close round-trip
 * is `2` here. This is leg-count semantics (NOT round-trips); `win_rate`
 * is the round-trip view. See the counter doc in `backtest.rs`.
 */
n_trades: number,
/**
 * Count of LLM-pipeline decision slots, including synthesized SL/TP exit
 * rows. Cadence-gated and filter-suppressed bars do not increment it (no
 * decision occurred). Filter wake/suppression accounting lives separately
 * in `xvision_filters::events::FilterSummary`.
 */
n_decisions: number,
/**
 * 2.5th percentile confidence bound for the run Sharpe bootstrap.
 */
sharpe_ci_low?: number,
/**
 * 97.5th percentile confidence bound for the run Sharpe bootstrap.
 */
sharpe_ci_high?: number,
/**
 * 2.5th percentile confidence bound for total-return percentage.
 */
return_ci_low?: number,
/**
 * 97.5th percentile confidence bound for total-return percentage.
 */
return_ci_high?: number,
/**
 * LLM-pipeline decisions emitted by the trader path.
 */
n_real_decisions?: number,
/**
 * Synthetic decisions emitted by deterministic engine paths.
 */
n_synthesized_decisions?: number,
/**
 * True when the run has fewer than the minimum trade legs for an honest
 * product-level statistical envelope.
 */
insufficient_sample?: boolean,
/**
 * Calendar used to annualize Sharpe going forward. `None` indicates a
 * legacy row computed before calendar-aware annualization.
 */
annualization_calendar?: string,
/**
 * Product trust grade (A-D) computed from trade count, CI, fee modeling,
 * and baseline-beat evidence. `None` indicates a legacy row.
 */
evidence_grade?: string,
/**
 * Total LLM inference cost for all decisions in this run (USD).
 * `None` when the model's pricing isn't in the catalog — in that case
 * `net_return_pct` is also `None` and a `MissingPricingData` finding
 * fires at run-finalize time.
 */
inference_cost_quote_total: number | null,
/**
 * Net return after subtracting LLM inference cost from gross return.
 * Math: `total_return_pct − (inference_cost_quote_total / capital_initial × 100)`.
 * `None` when `inference_cost_quote_total` is unavailable.
 */
net_return_pct: number | null,
/**
 * Automatic baseline comparison computed over the same bar slice the
 * strategy saw. `None` for old runs that predate baselines support or
 * for paper-mode runs where bars are not available post-hoc.
 */
baselines: BaselinesReport | null, };
