// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a provider's model catalog. Optional fields capture the
 * reality that not every provider exposes every fact — OpenAI's
 * `/v1/models` returns just `id` and `object`, so for those rows
 * `context_window` and `max_output_tokens` will be `None` and callers
 * must fall back to operator-supplied values or xvision's editorial
 * `ModelMetadata` overlay.
 *
 * `raw` keeps the provider's original entry so future fields can be
 * surfaced without re-fetching.
 */
export type ModelEntry = { 
/**
 * Provider-side model id as returned by the API. Used verbatim in
 * agent slot config and as the wire-level identifier when
 * dispatching. No normalization — preserving the provider's casing
 * and exact form is load-bearing for OpenRouter-style
 * `vendor/model` slugs.
 */
id: string, 
/**
 * Human-readable name when the provider supplies one. Anthropic and
 * OpenRouter set this; bare OpenAI-compat providers usually don't.
 */
display_name: string | null, 
/**
 * Total context window (input + output tokens). When `None`, the UI
 * should display "—" rather than fabricate a number.
 */
context_window: number | null, 
/**
 * Hard cap on output tokens for this model. When `Some`, the agent
 * slot's `max_tokens` resolver uses this as the ceiling instead of
 * the static `ModelMetadata::unknown_default` fallback.
 */
max_output_tokens: number | null, 
/**
 * Reasoning/thinking class. Some providers (OpenRouter, Anthropic)
 * surface this explicitly; for others it's inferred from the model
 * id by the fetcher. `None` means "unknown — assume standard".
 */
supports_reasoning: boolean | null, 
/**
 * Tool-use / function-calling support when the provider exposes it.
 */
supports_tools: boolean | null, 
/**
 * Price per 1M input tokens in USD. Only OpenRouter exposes this
 * today (Anthropic publishes pricing out-of-band).
 */
pricing_per_million_input_usd: number | null, 
/**
 * Price per 1M output tokens in USD.
 */
pricing_per_million_output_usd: number | null, 
/**
 * Provider's raw row, preserved verbatim. Lets future fields ride
 * out without a re-fetch and gives the dashboard a debug surface.
 */
raw: unknown, };
