// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetentionModeDto } from "./RetentionModeDto";

export type ObservabilityReport = { mode: RetentionModeDto, store_prompts: boolean, store_responses: boolean, store_tool_inputs: boolean, store_tool_outputs: boolean, redact_secrets: boolean, payload_ttl_days: number, max_payload_bytes: number, 
/**
 * True when the persisted config file exists. False means defaults
 * are in force — the UI uses this to render "Default" vs "Custom".
 */
persisted: boolean, };
