// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndicatorRef } from "./IndicatorRef";

/**
 * One side of a `Condition`. Discriminates by JSON/TOML type — see
 * module docs. `Serialize` is derived as `#[serde(untagged)]`;
 * `Deserialize` is hand-rolled via `OperandVisitor` so failures surface
 * per-shape (string vs number vs sequence) instead of the opaque
 * untagged-derive message.
 */
export type Operand = IndicatorRef | number | [number, number];
