// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperatorAttestationCreateRequest = { operator_initials: string, surface: string, signature: string | null, };
