// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * v1 operator catalog. Serde renames match the DSL form authors write
 * (`op = ">"` etc.). Unknown DSL strings are rejected at parse time by
 * serde; `parse.rs` converts those errors into `ParseError::UnknownOperator`
 * when it can detect the field-shape mismatch.
 */
export type Operator = ">" | "<" | ">=" | "<=" | "==" | "crosses_above" | "crosses_below" | "between";
