// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperatorAttestationDto = { id: string, operator_initials: string, surface: string, warning_text_hash: string, created_at: string, signature: string | null, };
