// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator catalog. Static operators use their literal DSL tokens;
 * parameterized operators encode the parameter in the token
 * (`above_for_3`, `crossed_above_5`, `slope_gt_4`,
 * `within_pct_1.5`, `zscore_gt_20`).
 */
export type Operator = ">" | "<" | ">=" | "<=" | "==" | "crosses_above" | "crosses_below" | "between" | `above_for_${number}` | `below_for_${number}` | `crossed_above_${number}` | `crossed_below_${number}` | `slope_gt_${number}` | `slope_lt_${number}` | `zscore_gt_${number}` | `zscore_lt_${number}` | `within_pct_${number}`;
