// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator catalog. Static operators use their literal DSL tokens;
 * parameterized operators encode the parameter in the token
 * (`above_for_3`, `crossed_above_5`, `slope_gt_4`,
 * `within_pct_1.5`, `zscore_gt_20`).
 */
export type Operator = "Gt" | "Lt" | "Gte" | "Lte" | "Eq" | "CrossesAbove" | "CrossesBelow" | "Between" | { "AboveFor": number } | { "BelowFor": number } | { "CrossedAbove": number } | { "CrossedBelow": number } | { "SlopeGt": number } | { "SlopeLt": number } | { "ZscoreGt": number } | { "ZscoreLt": number } | { "WithinPct": number };
