// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OptimizationGateRequest = { dev_metric: string | null, holdout_metric: string | null, parent_dev_score: number, child_dev_score: number, parent_holdout_score: number, child_holdout_score: number, gate_epsilon: number | null, gate_reason: string | null, };
