// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OptimizationGateDto = { optimization_id: string, dev_metric: string, holdout_metric: string, parent_dev_score: number, child_dev_score: number, parent_holdout_score: number, child_holdout_score: number, gate_epsilon: number, delta_dev: number, delta_holdout: number, gate_verdict: string, gate_reason: string, gated_at: string, };
