// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Order kind (subset of Alpaca's supported types).
 */
export type OrderKind = "market" | "limit" | "stop" | "stop_limit" | "trailing_stop";
