// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a simulated order in the backtest engine.
 *
 * # Variant notes
 *
 * - `Open` — order was submitted but has not triggered yet (e.g. a limit
 *   order whose price level has not been reached).
 * - `PartiallyFilled` — the volume cap in `eval-cost-model-per-bar-and-
 *   volume-share` bound; the cap-sized portion was filled and the remainder
 *   is conceptually still open. Full carry-to-next-bar mechanics are deferred.
 * - `Filled` — order filled completely.
 * - `Cancelled` — order was cancelled before filling.
 * - `Expired` — order expired (e.g. DAY TIF past session close).
 * - `Rejected` — order was rejected at order-emission time (broker rule
 *   violation, insufficient funds, etc.).
 */
export type OrderState = "open" | "partially_filled" | "filled" | "cancelled" | "expired" | "rejected";
