// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatternCreateRequest = { text: string, namespace: string, 
/**
 * Optional RFC3339 date. If `Some`, the Pattern is only recalled in
 * scenarios that start AFTER this timestamp (V2D leakage filter).
 * If `None`, the Pattern is operator-attested wisdom and is
 * recalled in every scenario.
 */
training_window_end: string | null, 
/**
 * Provenance fields MUST be absent — operator-seeded Patterns
 * never carry run/scenario/cycle attribution. We surface them on
 * the request so the validation error message is useful when an
 * integrator wires the wrong shape.
 */
run_id: string | null, scenario_id: string | null, cycle_idx: bigint | null, };
