// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgePredicate } from "./EdgePredicate";

/**
 * One directed edge in a `Graph` pipeline. Ignored for `Single` and
 * `Sequential`. Roles refer to `AgentRef.role` values present on the
 * owning strategy's `agents` list.
 */
export type PipelineEdge = { from_role: string, to_role: string, 
/**
 * Optional predicate evaluated against the upstream agent's
 * `FilterSignal.payload`. `None` (the default) = unconditional
 * edge — today's behavior. `Some(p)` fires the edge only when `p`
 * evaluates to `true`. Phase A persists the shape; Phase B
 * implements the evaluator.
 */
condition?: EdgePredicate, };
