// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the agents in a strategy wire together.
 *
 * - `Single`: exactly one agent; no edges.
 * - `Sequential`: agents execute in the order they appear in
 *   `Strategy.agents`. Edges are derived from that order so
 *   `edges` is empty under this kind.
 * - `Graph`: arbitrary DAG defined by `edges`. v1 does not ship a graph
 *   editor — the variant exists so on-disk JSON can carry a graph from
 *   a future version without breaking parse for current builds.
 */
export type PipelineKind = "single" | "sequential" | "graph";
