// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineEdge } from "./PipelineEdge";
import type { PipelineKind } from "./PipelineKind";

/**
 * Wiring spec for a strategy's agents.
 */
export type PipelineDef = { kind: PipelineKind, edges: Array<PipelineEdge>, };
