// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One directed edge in a `Graph` pipeline. Ignored for `Single` and
 * `Sequential`. Roles refer to `AgentRef.role` values present on the
 * owning strategy's `agents` list.
 */
export type PipelineEdge = { from_role: string, to_role: string, };
