// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { PositionSide } from "./PositionSide";

export type PositionPoint = { time: number, size: number, side: PositionSide, };
