// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report DTO returned by both `GET` and `PUT /api/settings/profile`.
 */
export type ProfileReport = { display_name: string | null, persisted: boolean, };
