// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report DTO returned by both `get` and `set`.
 */
export type ProfileReport = { 
/**
 * The persisted display name / handle, or `null` when unset.
 */
display_name: string | null, 
/**
 * True when the config file exists (i.e. the operator has saved a profile).
 */
persisted: boolean, };
