// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderRow = { name: string, 
/**
 * Stable string form — `"anthropic" | "openai-compat" | "local-candle"`.
 */
kind: string, base_url: string, 
/**
 * Env var holding the API key. Empty string for no-auth endpoints.
 */
api_key_env: string, 
/**
 * True if `api_key_env` is non-empty and the env var is set.
 */
api_key_set: boolean, 
/**
 * True for synthetic rows kept for wire compatibility.
 */
synthetic: boolean, 
/**
 * True if this provider is the workspace default (referenced by the
 * `[default_llm]` block). Removing it clears the workspace default.
 */
is_default: boolean, 
/**
 * Subset of the provider's catalog the operator has enabled for the
 * chat-rail / wizard dropdown. Empty until the operator picks
 * models via Settings → Providers → Manage models.
 */
enabled_models: Array<string>, };
