// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvalidProviderRow } from "./InvalidProviderRow";
import type { ProviderRow } from "./ProviderRow";

export type ProvidersReport = { providers: Array<ProviderRow>, 
/**
 * The currently-configured model on `[default_llm]`. Surfaced
 * alongside the per-row `is_default` flag so the Default-LLM UI
 * can pre-fill its model dropdown without a second fetch. None
 * when the operator hasn't set a default/model yet.
 */
default_model: string | null, 
/**
 * `[[providers]]` rows that failed validation and were skipped during the
 * lenient load (e.g. an uppercase name from a hand-edited config). Surfaced
 * so the UI can warn the operator and offer to remove them, instead of the
 * list silently going blank. Empty in the normal case.
 */
invalid?: Array<InvalidProviderRow>, };
