// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderModelEntry } from "./ProviderModelEntry";

export type ProviderModelsReport = { models: Array<ProviderModelEntry>, };
