// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderModelEntry = { 
/**
 * Canonical model id used in `/chat/completions` calls.
 */
id: string, 
/**
 * Human-readable label when the provider exposes one (Anthropic does;
 * most OpenAI-compat providers don't). Falls back to `id` on the UI.
 */
display_name: string | null, 
/**
 * Free-form provider tag — `openai`, `anthropic`, `meta`, etc.
 * Surfaced as a sub-label so OpenRouter's "anthropic/claude-…" rows
 * can be filtered alongside DeepSeek's "deepseek-…".
 */
owned_by: string | null, 
/**
 * Context window if the provider returns one. Optional.
 */
context_length: number | null, };
