// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminant for why eval-launch refused a `(provider, model)`. Replaces
 * the historic flat `"provider '{name}' is not configured"` string so
 * operators reading CLI output know whether to add a key or flip a toggle.
 */
export type ProviderUnavailableReason = "provider_unknown" | "provider_disabled" | "key_missing" | "model_disabled";
