// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUnavailableReason } from "./ProviderUnavailableReason";

export type ProviderUnavailable = { provider: string, reason: ProviderUnavailableReason, 
/**
 * Set when the caller named a specific model. None means the caller
 * only asked about provider-level launchability.
 */
model: string | null, 
/**
 * Human-readable hint — names the env var to set or the toggle to
 * flip. Eval refusal renders this verbatim into the CLI error.
 */
hint: string, };
