// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderRow = { name: string, 
/**
 * Stable string form — `"anthropic" | "openai-compat" | "local-candle"`.
 */
kind: string, base_url: string, 
/**
 * Env var holding the API key. Empty string for no-auth endpoints.
 */
api_key_env: string, 
/**
 * True if `api_key_env` is non-empty and the env var is set.
 */
api_key_set: boolean, 
/**
 * True for synthetic rows (name starts with `_`) — read-only.
 */
synthetic: boolean, 
/**
 * True if removing this entry would orphan the `[intern]` workspace
 * default slot. UI should disable the delete button.
 */
referenced_by_intern: boolean, };
