// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderOverride = { 
/**
 * Provider name as it appears in `[[providers]]` (e.g. `anthropic`,
 * `openrouter`). Must be paired with a concrete `model` — passing
 * one without the other is a CLI/API usage error.
 */
provider: string, 
/**
 * Model id to use for the duration of this run. Must be enabled on
 * the named provider (verified through
 * `effective_providers::resolve_provider`).
 */
model: string, };
