// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/** A single position row inside a reconciliation outcome. */
export type ReconcilePositionRow = {
  asset: string,
  broker_size: number,
  expected_size: number,
  broker_mtm_usd: number | null,
  expected_mtm_usd: number | null,
  side: string,
  material: boolean,
  reason: string | null,
};

/**
 * Result of comparing broker positions to expected positions.
 * Returned by `POST /api/eval/runs/:id/reconcile`.
 */
export type ReconcileOutcome = {
  matched: boolean,
  broker_total_usd: number | null,
  expected_total_usd: number | null,
  positions: Array<ReconcilePositionRow>,
};
