// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One result row in `refresh_all`. Successful rows carry the model
 * count and source url; failed rows carry an error string the UI
 * surfaces under that provider's row.
 */
export type RefreshOutcome = { provider: string, ok: boolean, model_count: number | null, error: string | null, source_url: string | null, };
