// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefreshPolicy = { "policy": "NeverRefresh" } | { "policy": "RefreshIfOlderThan", duration_secs: bigint, };
