// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegenIdentityReport = { 
/**
 * New public key in hex-encoded form. Operator copies this if they
 * need to publish it elsewhere.
 */
pubkey_hex: string, 
/**
 * Filesystem path the new key was written to.
 */
key_path: string, };
