// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenameAgentRoleReq = { strategy_id: string, role: string, new_role: string, };
