// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplayMode = { "mode": "Continuous" } | { "mode": "Stepped" } | { "mode": "Accelerated", speed: number, } | { "mode": "Realtime" };
