// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Requirement = {
/**
 * Display label: `"provider/model"` for a model, the skill name (or its
 * id when unresolvable) for a skill, the tool name for a tool.
 */
name: string,
/**
 * One of `"model"`, `"skill"`, `"tool"`.
 */
kind: string, satisfied: boolean,
/**
 * Why an unsatisfied requirement fails — the `ProviderUnavailable`
 * reason discriminant for models, a short note for missing skills.
 */
reason?: string,
/**
 * Human-readable next step (e.g. the provider hint pointing at Settings).
 */
hint?: string, };
