// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One requirement a strategy places on the buyer's machine — a model the
 * agents need, a skill they reference, or a tool they may invoke.
 *
 * QA #4 + Q1: a purchased strategy opens fully, but its models/skills may
 * not be configured locally. The Strategy detail page renders these so the
 * operator sees each gap (and whether it blocks eval). Only `model`
 * requirements gate eval/go-live; skills surface as warnings and tools are
 * purely informational (the engine has no installed-MCP inventory).
 */
export type Requirement = { 
/**
 * Display label: `"provider/model"` for a model, the skill name (or its
 * id when unresolvable) for a skill, the tool name for a tool.
 */
name: string, 
/**
 * One of `"model"`, `"skill"`, `"tool"`.
 */
kind: string, satisfied: boolean, 
/**
 * Why an unsatisfied requirement fails — the `ProviderUnavailable`
 * reason discriminant for models, a short note for missing skills.
 */
reason: string | null, 
/**
 * Human-readable next step (e.g. the provider hint pointing at Settings).
 */
hint: string | null, };
