// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies *why* a retry was issued, so downstream surfaces (review
 * queue, lineage ribbon, audit log readers) can distinguish a deliberate
 * rerun of a `Completed` run from a recovery retry of a `Failed` or
 * `Cancelled` run. Derived deterministically from source status —
 * callers do not supply it.
 */
export type RetryReason = "failure_recovery" | "manual_rerun";
