// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strict verdict tag the review must return. Persisted as a plain string
 * so the DB stays schema-loose if downstream profiles need to evolve the
 * allowed values without a migration.
 */
export type ReviewVerdict = "promising" | "weak" | "failed" | "inconclusive";
