// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewAnnotation = { idx: number, side: string, type: string, title: string, body: string, conf: number, action: string, danger: boolean, ts?: number | null, };
