// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatActionPayload } from "./ChatActionPayload";
import type { ChatRunListPayload } from "./ChatRunListPayload";
import type { ChatStrategyPayload } from "./ChatStrategyPayload";
import type { InlineAction } from "./InlineAction";
import type { InlineChartPayload } from "./InlineChartPayload";

export type RichContentBlock = { "type": "inline_chart" } & InlineChartPayload | { "type": "run_list" } & ChatRunListPayload | { "type": "strategy_card" } & ChatStrategyPayload | { "type": "action_card" } & ChatActionPayload | { "type": "choice_chips", chips: Array<InlineAction>, };
