// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgePredicate } from "./EdgePredicate";

export type RouteGraphEdge = { from_role: string, to_role: string, condition?: EdgePredicate, };
