// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteContextField = "market_snapshot" | "tool_state" | "available_targets" | "regime_summary";
