// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RouteDiagnosticReason = { code: string, message: string, blocking: boolean, };
