// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteContextField } from "./RouteContextField";
import type { RouteDiagnosticReason } from "./RouteDiagnosticReason";

export type RouteReadiness = { routed: boolean, context_fields: Array<RouteContextField>, launchable: boolean, reasons: Array<RouteDiagnosticReason>, };
