// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ChartBar } from "./ChartBar";
import type { ChartEquityPoint } from "./ChartEquityPoint";
import type { ChartMarkers } from "./ChartMarkers";
import type { DrawdownPoint } from "./DrawdownPoint";
import type { Indicators } from "./Indicators";
import type { PositionPoint } from "./PositionPoint";
import type { TimeWindow } from "./TimeWindow";

export type RunChartPayload = {
    run_id: string,
    scenario_id: string,
    asset: string,
    granularity: string,
    time_window: TimeWindow,
    bars: Array<ChartBar>,
    indicators: Indicators,
    equity: Array<ChartEquityPoint>,
    drawdown: Array<DrawdownPoint>,
    position: Array<PositionPoint>,
    markers: ChartMarkers,
};
