// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionRowDto } from "./DecisionRowDto";
import type { EquityPoint } from "./EquityPoint";
import type { FilterEventV1 } from "./FilterEventV1";
import type { FilterSummary } from "./FilterSummary";
import type { RunSummary } from "./RunSummary";

/**
 * Full run detail — `RunSummary` plus the decision rows and equity samples.
 * Used by `/api/eval/runs/:id`.
 */
export type RunDetail = { summary: RunSummary, decisions: Array<DecisionRowDto>, equity_curve: Array<EquityPoint>, filter_events: Array<FilterEventV1>, filter_summaries: Array<FilterSummary>, signals_used?: Array<string> | null, };
