// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEquityPoint } from "./ChartEquityPoint";

export type RunEquitySeries = { run_id: string, label: string, scenario_id: string, final_pnl_usd: number, max_drawdown_pct: number, sharpe: number | null, equity_normalised: Array<ChartEquityPoint>, };
