// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An eval-run that included a given agent. Empty in v1 — strategies don't
 * reference agents yet, so we can't attribute runs to agents.
 */
export type RunRef = { run_id: string, scenario_id: string, status: string, };
