// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunSummary = { id: string, strategy_bundle_hash: string, scenario_id: string, 
/**
 * Lower-case discriminant ("backtest" | "paper").
 */
mode: string, 
/**
 * Lower-case discriminant ("queued" | "running" | "completed" | "failed" | "cancelled").
 */
status: string, started_at: string, completed_at: string | null, 
/**
 * Sharpe ratio if metrics finalized; `None` otherwise.
 */
sharpe: number | null, 
/**
 * Max drawdown % if metrics finalized; `None` otherwise.
 */
max_drawdown_pct: number | null, 
/**
 * Total return % if metrics finalized; `None` otherwise.
 */
total_return_pct: number | null, error: string | null, };
