// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §2-D — per-run trajectory-recording mode. The operator's chosen driver
 * for Cline trajectory recording (replaces the §2-B `XVN_TRAJECTORY_RECORD`
 * env gate). The caller declares intent on the request; the engine acts on it.
 *
 * * `Live` (default) — no recording. Byte-identical to the pre-§2-D /
 *   pre-§2-B behaviour for backtest + live + non-record Cline runs:
 *   `trajectory_mode != Record` ⇒ `recording_request = None` ⇒ the §2-B
 *   `None` spawn path (no event sink bound).
 * * `Record` — mint a trajectory recording for the run's primary recorded
 *   slot and bind the event sink so frames persist into the store.
 *
 * Replay through the engine eval path is intentionally NOT a variant here.
 * Adding engine-eval replay would require threading a recording id + store
 * into every slot dispatch — out of scope for §2-D.
 */
export type RunTrajectoryMode = "live" | "record";
