// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated token + cost figures for one eval run.
 *
 * Sourced from the `model_calls` table joined to the run via the
 * observability span chain (see [`aggregate_run_token_totals`]). The
 * `cost_estimate_complete` flag tracks whether every contributing
 * `model_calls.cost_usd` had a non-null value — when `false`, the
 * reported `cost_usd` is a strict lower bound and the operator should
 * know.
 */
export type RunTokenTotals = { 
/**
 * Sum of `model_calls.input_token_count` across the run.
 * `None` when no model_calls landed for this run.
 */
input_tokens: bigint | null, 
/**
 * Sum of `model_calls.output_token_count` across the run.
 * `None` when no model_calls landed for this run.
 */
output_tokens: bigint | null, 
/**
 * Sum of `model_calls.cost_usd`. `None` when every contributing row
 * had `cost_usd = NULL`, or no model_calls landed at all.
 */
cost_usd_estimate: number | null, 
/**
 * `true` iff every model_call row contributing to `input_tokens` /
 * `output_tokens` had a known `cost_usd` (no NULLs were skipped).
 * When `false`, `cost_usd_estimate` is a lower bound. The struct
 * default is `false` (bool default) — see [`RunTokenTotals::default`]
 * for the no-rows / failure-mode case where the flag is paired with
 * `cost_usd_estimate = None` and operationally means "no signal,
 * no claim".
 */
cost_estimate_complete: boolean, 
/**
 * Count of model_call rows aggregated. Useful for debugging "why is
 * my cost null" — when this is 0, the observability bus wasn't wired
 * (typical for very old runs or pure-rust-baseline arms).
 */
model_call_count: bigint, };
