// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SafetyLimits = { 
/**
 * Maximum cumulative notional value (USD) that may be submitted across
 * all orders in this run. `None` = no cap.
 */
notional_cap_usd: number | null, 
/**
 * Maximum number of orders that may be submitted in this run.
 * `None` = no cap.
 */
max_order_count: number | null, 
/**
 * Maximum portfolio leverage (Crypto perps only). `None` = no cap.
 */
max_leverage: number | null, 
/**
 * Maximum allowed drawdown from peak equity, as a percentage.
 * Breach triggers a circuit-breaker abort. `None` = no cap.
 */
max_loss_pct: number | null, };
