// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheStatus } from "./CacheStatus";
import type { ChartBar } from "./ChartBar";
import type { ChartEquityPoint } from "./ChartEquityPoint";

export type ScenarioPreviewPayload = { cache_key: string, asset: string, granularity: string, bars: Array<ChartBar>, cache_status: CacheStatus, baseline_equity: Array<ChartEquityPoint> | null, };
