// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { TimeWindow } from "./TimeWindow";
import type { VenueSettings } from "./VenueSettings";

/**
 * Mutations applied on top of a parent scenario when cloning. `None`
 * means "inherit from parent". `notes` is intentionally a bare
 * `Option<String>` so the clone starts with empty notes by default.
 */
export type ScenarioMutations = { display_name: string | null, description: string | null, time_window: TimeWindow | null, asset: Array<AssetRef> | null, granularity: string | null, venue: VenueSettings | null, tags: Array<string> | null, notes: string | null, };
