// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheStatus } from "./CacheStatus";
import type { ChartBar } from "./ChartBar";
import type { Scenario } from "./Scenario";

export type ScenarioChartPayload = { scenario: Scenario, bars: Array<ChartBar>, cache_status: CacheStatus, };
