// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetClass } from "./AssetClass";
import type { AssetRef } from "./AssetRef";
import type { BarCachePolicy } from "./BarCachePolicy";
import type { CalendarRef } from "./CalendarRef";
import type { DataSource } from "./DataSource";
import type { QuoteCurrency } from "./QuoteCurrency";
import type { ReplayMode } from "./ReplayMode";
import type { ScenarioSource } from "./ScenarioSource";
import type { TimeWindow } from "./TimeWindow";
import type { VenueSettings } from "./VenueSettings";

export type Scenario = { id: string, parent_scenario_id: string | null, source: ScenarioSource, display_name: string, description: string, tags: Array<string>, notes: string | null, asset_class: AssetClass, asset: Array<AssetRef>, quote_currency: QuoteCurrency, time_window: TimeWindow, granularity: string, timezone: string, calendar: CalendarRef, data_source: DataSource, venue: VenueSettings, replay_mode: ReplayMode, bar_cache_policy: BarCachePolicy, created_at: string, created_by: string, archived_at: string | null, };
