// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetClass } from "./AssetClass";
import type { BarCachePolicy } from "./BarCachePolicy";
import type { CalendarRef } from "./CalendarRef";
import type { DataSource } from "./DataSource";
import type { QuoteCurrency } from "./QuoteCurrency";
import type { ReplayMode } from "./ReplayMode";
import type { SafetyLimits } from "./SafetyLimits";
import type { ScenarioSource } from "./ScenarioSource";
import type { TimeWindow } from "./TimeWindow";
import type { VenueLabel } from "./VenueLabel";
import type { VenueSettings } from "./VenueSettings";

export type Scenario = { id: string, parent_scenario_id: string | null, source: ScenarioSource, display_name: string, description: string, tags: Array<string>, notes: string | null, asset_class: AssetClass, quote_currency: QuoteCurrency, time_window: TimeWindow, timezone: string, calendar: CalendarRef, data_source: DataSource, venue: VenueSettings, replay_mode: ReplayMode,
/**
 * Initial trading capital for this evaluation scenario. Moved back onto
 * Scenario (from Strategy) so backtest results are reproducible
 * independent of which strategy is run against the scenario.
 */
capital: { initial: number, currency: string }, bar_cache_policy: BarCachePolicy,
/**
 * Number of bars to pre-fetch from immediately before
 * `time_window.start` so per-decision context (indicators, trader
 * `bar_history` slice) has real history at bar 1. Defaults to
 * [`DEFAULT_WARMUP_BARS`] for new scenarios; legacy rows whose
 * `body_json` predates this field hydrate to the same default via
 * `serde(default)`.
 */
warmup_bars: number,
/**
 * Broad market-regime character.
 */
regime_label: string | null,
/**
 * Per-bar volatility bucket.
 */
volatility_label: string | null,
/**
 * Net price direction over the window.
 */
trend_direction: string | null,
/**
 * `true` when labels were derived by `xvn scenario classify`;
 * `false` (default) when set by the operator.
 */
regime_derived: boolean, created_at: string, created_by: string, archived_at: string | null,
/**
 * Coarse venue classification. Drives the UI badge (green/amber/red) and
 * the confused-deputy gate (Paper scenario must not hit a Live broker).
 * Defaults to `Paper` for all existing scenarios via `serde(default)`.
 */
venue_label: VenueLabel,
/**
 * Optional per-run safety limits. When set, the gate checks these at
 * every broker submit and aborts the run on breach.
 */
safety_limits: SafetyLimits | null, };
