// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three-valued patch for `Agent.scope_strategy_id`. The outer
 * `Option` distinguishes "leave the column alone" (`None`) from "set
 * to a value" (`Some(Set(_))`) and "clear to NULL" (`Some(Clear)`).
 */
export type ScopePatch = { "set": string } | "clear";
