// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDefinition } from "./RouteDefinition";

export type SetRouteReq = { strategy_id: string, route: RouteDefinition, };
