// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillKind } from "./SkillKind";

export type Skill = { skill_id: string, name: string, description: string, kind: SkillKind, 
/**
 * Free-form per-kind config blob. v1 doesn't validate against a
 * schema — that's a per-kind concern that lands when a kind's
 * runtime application surfaces.
 */
config: Record<string, unknown>, archived: boolean, created_at: string, updated_at: string, };
