// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlippageModel = { "model": "linear", bps: number, } | { "model": "none" } | { "model": "volume_share", 
/**
 * Quadratic price-impact coefficient (dimensionless, default 0.1).
 */
price_impact: number, 
/**
 * Maximum fraction of bar volume that can be filled. Cap binding
 * emits a `volume_share_excess` finding (default 0.025 = 2.5%).
 */
volume_limit: number, };
