// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Run-terminating limits for a Live run. At least one limit must be set;
 * the engine evaluates whichever fires first.
 *
 * `time_limit_secs` is wall-clock seconds since run start, `bar_limit` is
 * the bar count consumed from the [`crate::eval::executor::BarSource`],
 * `decision_limit` is the LLM-dispatch count, and `trade_limit` is the
 * completed filled-trade count.
 */
export type StopPolicy = { 
/**
 * Wall-clock seconds since run start; the run terminates at or before
 * the first bar-close past this point. Capped at
 * [`LIVE_RUN_MAX_TIME_LIMIT_SECS`] (30 days).
 */
time_limit_secs: bigint | null, 
/**
 * Number of bars consumed before termination.
 */
bar_limit: number | null, 
/**
 * Number of LLM dispatches before termination. Useful for cost-bounded
 * shake-down runs.
 */
decision_limit: number | null, 
/**
 * Number of completed filled trades before termination.
 */
trade_limit: number | null, };
