// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial-update body for [`update_metadata`]. All fields are
 * optional; `None` means "leave the existing value unchanged". A
 * patch with every field `None` is a valid no-op and round-trips the
 * stored strategy untouched.
 *
 * Scope is deliberately narrow: only the four operator-editable
 * top-level manifest fields a typo in the create wizard could land
 * on. The strategy `id`, `creator`, `template`, `published_at`,
 * `risk_preset_or_config`, `agents`, `pipeline`, `risk`, and
 * `mechanical_params` are out of scope — they either have dedicated
 * sub-routes (slot/agents/pipeline/risk) or are immutable
 * post-create.
 *
 * Color clear convention: `color: ""` (empty string) explicitly
 * clears the stored color. `color: null` / omitted leaves it unchanged.
 */
export type StrategyMetadataPatch = { display_name: string | null, plain_summary: string | null, asset_universe: Array<string> | null, color?: string | null, };
