// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a strategy came from: hand-authored (`user`) or minted by the
 * autooptimizer (`optimizer`, i.e. its bundle hash is a lineage node).
 */
export type StrategyOrigin = "user" | "optimizer";
