// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Requirement } from "./Requirement";

export type StrategyRequirements = { requirements: Array<Requirement>,
/**
 * True iff every `kind == "model"` requirement is satisfied. Skills and
 * tools never affect this — they don't gate eval.
 */
all_models_satisfied: boolean, };
