// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { PipelineDef } from "./PipelineDef";

export type StrategyAgentsOut = { strategy_id: string, agents: Array<AgentRef>, pipeline: PipelineDef, };
