// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StrategySummary = { agent_id: string, display_name: string, template: string, decision_cadence_minutes: number, tags: Array<string>,
/**
 * Model summary for attached AgentRefs. Falls back to legacy slot config
 * and shows the first unique model plus a count when multiple are present.
 */
model?: string, };
