// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivationMode } from "./ActivationMode";
import type { ProviderModelPair } from "./ProviderModelPair";
import type { StrategyOrigin } from "./StrategyOrigin";

export type StrategySummary = { agent_id: string, display_name: string, template: string, decision_cadence_minutes: number, tags: Array<string>, 
/**
 * Optional per-strategy display color from the manifest. Chart surfaces
 * use it before falling back to the stable compare palette.
 */
color: string | null, 
/**
 * Model summary for attached AgentRefs. Falls back to legacy slot config
 * and shows the first unique model plus a count when multiple are present.
 */
model: string | null, 
/**
 * Unique provider names required by this strategy's executable slots.
 */
providers: Array<string>, 
/**
 * Unique model ids required by this strategy's executable slots.
 */
models: Array<string>, 
/**
 * Explicit provider-model pairs required by this strategy's executable slots.
 */
provider_models: Array<ProviderModelPair>, 
/**
 * Number of attached strategy AgentRefs. Deterministic filters are not
 * agents and must not be counted here.
 */
agent_count: number, 
/**
 * Number of deterministic strategy-level filters.
 */
filter_count: number, 
/**
 * Strategy decision activation mode: `filter_gated`, `every_bar`, or
 * `compiled_rules`.
 */
activation_mode: ActivationMode, 
/**
 * Asset universe from the strategy manifest (e.g. `["BTC/USD", "ETH/USD"]`).
 */
asset_universe: Array<string>, 
/**
 * Execution mode as a snake_case string (e.g. `"per_asset"`, `"portfolio"`).
 */
execution_mode: string, 
/**
 * blake3 hex hash of the strategy bundle's canonical JSON — the id
 * older CLI-launched eval runs carry in `eval_runs.agent_id` (migration
 * 014 renamed `strategy_bundle_hash` → `agent_id` without changing the
 * value), and the key of autooptimizer `lineage_nodes`. `None` only if
 * the bundle fails to serialize.
 */
bundle_hash?: string, 
/**
 * `optimizer` when this strategy's bundle hash appears in the
 * autooptimizer lineage (`lineage_nodes`) — such strategies are
 * evaluated inside optimizer cycles and the dashboard must not nag
 * about them missing direct eval runs. `user` otherwise.
 */
origin: StrategyOrigin, 
/**
 * True when at least one COMPLETED eval run references this strategy —
 * keyed by workspace ULID or by bundle hash — over the FULL `eval_runs`
 * table (not a page of it).
 */
evaluated: boolean, 
/**
 * `completed_at` (RFC3339) of the most recent completed eval run
 * referencing this strategy. Absent when `evaluated` is false.
 */
last_eval_completed_at?: string, };
