// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunEquitySeries } from "./RunEquitySeries";

export type StrategyChartPayload = { strategy_id: string, run_series: Array<RunEquitySeries>, 
/**
 * `(scenario_id, display_name)` pairs for every scenario referenced by
 * the runs. Deduplicated and sorted by scenario_id.
 */
scenarios: Array<[string, string]>, };
