// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StrategySummary = { agent_id: string, template: string,
/**
 * Model requirement of the bundle's primary slot — trader if set,
 * otherwise the first configured slot in (trader, intern, regime)
 * order. None when no slot has a model_requirement. Surfaced so the
 * strategies list page can render a Model column without fetching
 * each bundle separately.
 */
model?: string, };
