// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDiagnostics } from "./AgentDiagnostics";
import type { RouteReadiness } from "./RouteReadiness";
import type { UnmetTool } from "./UnmetTool";

export type StrategyDiagnostics = { strategy_id: string, per_agent: Array<AgentDiagnostics>, unregistered_tools: Array<UnmetTool>, has_decision_path: boolean, route: RouteReadiness, launchable: boolean, };
