// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A strategy that references an agent. Empty in v1 — see plan §Downstream impact.
 */
export type StrategyRef = { strategy_id: string, name: string, };
