// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a would-have-triggered bar produced no LLM wakeup.
 *
 * `None` on the event means "no suppression"; the event was either a
 * real trip (`triggered = true`) or a non-active outcome
 * (Inactive / Warming / Hold) where there was nothing to suppress.
 */
export type SuppressedReason = "in_position" | "cooldown" | "daily_cap";
