// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestConnectionReport = { ok: boolean, latency_ms: number,
/**
 * Number of models the catalog returned. 0 on error or when the
 * provider's catalog endpoint genuinely returned nothing.
 */
model_count: number,
/**
 * Failure message when `ok` is false. None on success.
 */
error?: string, };
