// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Bar timeframe as a string (e.g. "1h"). v1 keeps this stringly-typed; formal Timeframe parsing lives in other crates.
 */
export type Timeframe = string;
