// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool call record embedded in a `DecisionTrace`.
 */
export type ToolCall = { 
/**
 * Tool name as declared in the strategy's tool registry.
 */
name: string, 
/**
 * Input JSON blob (open-ended).
 */
input: unknown, };
