// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolDiagnostic = { name: string, registered: boolean, description: string | null, };
