// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { TradeSide } from "./TradeSide";

export type TradeMarker = {
    time: number,
    side: TradeSide,
    price: number,
    size: number,
    fee: number,
    pnl_realized: number | null,
    decision_index: number,
    justification: string | null,
};
