// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UndoForgetRequest = { 
/**
 * Exact namespace whose soft-deleted rows should be restored.
 * Mutually exclusive with `agent`.
 */
namespace: string | null, 
/**
 * Shorthand for `namespace = "agent:<id>"`.
 */
agent: string | null, 
/**
 * Optional RFC3339 lower bound. Rows whose `forgotten_at` is
 * strictly older than this are NOT restored. Defaults to
 * `now - XVN_MEMORY_FORGET_GRACE_DAYS` so an operator restoring
 * without an explicit `since` gets the natural "everything still
 * in the grace window" behavior.
 */
since: string | null, };
