// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UndoForgetResponse = { restored: bigint, 
/**
 * RFC3339 lower bound that was applied (resolved from
 * `since` or computed from `grace_days`).
 */
since: string, };
