// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial-update request. Only provided fields are changed; omitted fields
 * keep their persisted (or default) value.
 */
export type UpdateMemoryRequest = { 
/**
 * New embedder source as a flat string (`off`/`local`/`auto`/<provider>).
 */
embedder: string | null, chat_enabled: boolean | null, optimizer_enabled: boolean | null, 
/**
 * New embedding model id. An empty/whitespace string clears it back to
 * the resolver default (stored as `None`); `None` here leaves the
 * persisted value untouched (partial update).
 */
embedder_model: string | null, 
/**
 * New base URL for the `"custom"` embedder source. An empty/whitespace
 * string clears it (stored as `None`); `None` here leaves the persisted
 * value untouched (partial update). Used verbatim (trimmed) — never
 * rewritten, so the operator-typed `/v1` survives.
 */
embedder_base_url: string | null, };
