// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial-update body for `PUT /api/settings/profile`. `display_name: ""`
 * (or whitespace) clears the handle; `null` leaves it untouched.
 */
export type UpdateProfileRequest = { display_name?: string | null, };
