// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial-update request. Only provided fields are changed; omitted fields
 * keep their persisted (or default) value.
 */
export type UpdateMemoryRequest = { 
/**
 * New embedder source as a flat string (`off`/`local`/`auto`/<provider>).
 */
embedder: string | null, chat_enabled: boolean | null, optimizer_enabled: boolean | null, };
