// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillKind } from "./SkillKind";

export type UpdateSkillRequest = { name: string | null, description: string | null, kind: SkillKind | null, config: Record<string, unknown> | null, };
