// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial-update request. `display_name: Some("")` (or whitespace) clears the
 * handle; `None` leaves it untouched (partial update).
 */
export type UpdateProfileRequest = { display_name: string | null, };
