// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSlot } from "./AgentSlot";

export type UpdateAgentRequest = { name: string | null, description: string | null, tags: Array<string> | null, slots: Array<AgentSlot> | null, };
