// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type ValidationDiagnostic = { 
/**
 * Stable machine-readable code (e.g., "name_empty", "slot_name_duplicate").
 */
code: string, severity: Severity, message: string, 
/**
 * Optional pointer into the agent payload (e.g., "name", "slots[0].provider").
 */
field: string | null, };
