// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fees } from "./Fees";
import type { FillModel } from "./FillModel";
import type { LatencyModel } from "./LatencyModel";
import type { SlippageModel } from "./SlippageModel";
import type { Venue } from "./Venue";

export type VenueSettings = { venue: Venue, fees: Fees, slippage: SlippageModel, latency: LatencyModel, fill_model: FillModel, };
