// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fees } from "./Fees";
import type { SlippageModel } from "./SlippageModel";

/**
 * Per-asset cost override matched by a glob pattern on the venue symbol
 * (e.g. `"BTC/USD"`, `"*USD"`, `"NVDA*"`).
 *
 * Override precedence (highest wins): per-bar array → per-asset override →
 * scenario default.
 */
export type VenueOverride = { 
/**
 * Glob pattern matched against the asset's `venue_symbol` (e.g. `"BTC/USD"`).
 */
symbol_pattern: string, 
/**
 * Override fee schedule. `None` means fall through to scenario default.
 */
fees: Fees | null, 
/**
 * Override slippage model. `None` means fall through to scenario default.
 */
slippage: SlippageModel | null, };
