// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VetoMarker = { time: number, price: number, reason: string, decision_index: number, };
