// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the trader agent is re-invoked while a position is open in the
 * filter's asset. Controls per-bar polling cost during a hold; it does NOT
 * change entry firing (a flat asset always fires on a fresh trip).
 *
 * Serializes to snake_case tokens: `always`, `on_invalidation_or_target_only`,
 * `never`. The runtime default is [`WakeInPosition::OnInvalidationOrTargetOnly`]
 * (see `default_wake_in_position`).
 */
export type WakeInPosition = "always" | "on_invalidation_or_target_only" | "never";
