// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletStatus = { 
/**
 * Mantle RPC URL configured? (env var presence).
 */
rpc_url_set: boolean, 
/**
 * Operator-controlled wallet private key configured? (env var presence
 * only — values never leave the process).
 */
wallet_key_set: boolean, };
