// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableWipe } from "./TableWipe";

export type WipeDbReport = { 
/**
 * `(table_name, rows_deleted)` for every user table touched.
 * Ordering matches `sqlite_master` enumeration order.
 */
tables: Array<TableWipe>, 
/**
 * Rows summed across `tables`. Useful for the UI's confirmation
 * toast without re-summing.
 * Rows summed across `tables`. `u32` rather than `u64` so ts-rs
 * emits a TS `number` instead of `bigint` (4B rows is plenty for
 * any user table).
 */
total_rows_deleted: number, };
