// /chart-lab/dashboards/overview — fixture render of B1's
// DarkMinimalDashboard. Used as the visual regression target instead of
// the production route (which depends on the backend stub being up).
//
// See docs/superpowers/specs/2026-05-21-chart-rework-klinecharts-uplot.md
// §4A.7.

import fixture from "@/components/chart/v2/__fixtures__/multi-strategy-equity.json";
import { DarkMinimalDashboard } from "@/components/chart/v2/surfaces/DarkMinimalDashboard";
import type { MultiStrategyEquityBundle } from "@/components/chart/v2/types";

export function ChartLabDashboardOverview() {
  // The fixture file is generated by scripts/gen-chart-v2-fixtures.ts
  // and matches the shape of MultiStrategyEquityBundle. Cast is safe
  // because the generator and the type are co-authored.
  const payload = fixture as unknown as MultiStrategyEquityBundle;
  return (
    <div className="space-y-4">
      <div className="text-[12px] text-text-3">
        Rendered against{" "}
        <code className="text-text-2">multi-strategy-equity.json</code> fixture.
        Production route at <code className="text-text-2">/charts/overview</code>{" "}
        fetches the same shape from <code>/api/v2/charts/dashboards/overview</code>.
      </div>
      <DarkMinimalDashboard payload={payload} />
    </div>
  );
}
