// Nanochat + Autoresearcher API client.
//
// Routes (all new — no existing module to merge into):
//   GET  /api/nanochat/checkpoints                   → NanochatCheckpoint[]
//   GET  /api/nanochat/checkpoints/:model_id         → NanochatCheckpoint
//   POST /api/nanochat/checkpoints/:model_id/approve → ApproveCheckpointOut (idempotent)
//   POST /api/autoresearch/runs                      → StartRunOut
//   POST /api/autoresearch/runs/:run_id/stop         → {}
//   GET  /api/autoresearch/runs                      → AutoresearchRunSummary[]
//   GET  /api/autoresearch/runs/:run_id              → AutoresearchRunDetail
//   GET  /api/autoresearch/runs/:run_id/stream       → SSE (consumed by useAutoresearchStream hook)
//   GET  /api/autoresearch/runs/:run_id/experiments  → AutoresearchExperiment[]
//
// `CheckpointRef` mirrors `crates/xvision-engine/src/strategies/agent_ref.rs`
// (generated by ts-rs into frontend/web/src/api/types.gen/ when the Rust
// feature flag is enabled — hand-rolled here until the codegen lands, matching
// the exact wire shape).

import { apiFetch } from "@/api/client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

// ─── Wire types ────────────────────────────────────────────────────────────────

/** Parsed shape of `trained_models.input_spec`. NOTE: the wire carries
 * `input_spec` as a RAW JSON STRING (the route returns the stored column
 * verbatim), so consumers must `parseInputSpec()` it — do NOT read
 * `checkpoint.input_spec.window_bars` directly (it's a string). */
export type InputSpec = {
  window_bars: number;
  indicators: string[];
  normalization: string;
};

/** Parse the raw `input_spec` JSON string into an `InputSpec`. Returns null
 * on malformed/empty input rather than throwing. */
export function parseInputSpec(raw: string | null | undefined): InputSpec | null {
  if (!raw) return null;
  try {
    const v = JSON.parse(raw) as Partial<InputSpec>;
    if (typeof v.window_bars !== "number" || !Array.isArray(v.indicators)) return null;
    return {
      window_bars: v.window_bars,
      indicators: v.indicators,
      normalization: typeof v.normalization === "string" ? v.normalization : "none",
    };
  } catch {
    return null;
  }
}

export type NanochatCheckpoint = {
  model_id: string;
  display_name: string;
  source_strategy_id: string | null;
  source_strategy_name: string | null;
  run_tag: string;
  checkpoint_path: string;
  weights_format: string;
  weights_sha256: string;
  /** Raw JSON string (see {@link parseInputSpec}); NOT a parsed object. */
  input_spec: string;
  base_model: string;
  label_strategy: "price_forward" | "outcome_imitation";
  label_config: Record<string, unknown>;
  best_acc: number | null;
  best_loss: number | null;
  holdout_samples: number | null;
  promoted: boolean;
  live_approved: boolean;
  created_at: string;
  autoresearch_run_id: string | null;
};

export type ApproveCheckpointOut = {
  model_id: string;
  live_approved: boolean;
};

/** `label_strategy` determines which fields of `label_config` are used. */
export type LabelConfig =
  | { price_forward_threshold: number }
  | { outcome_filter?: Record<string, unknown> };

export type StartRunRequest = {
  source_strategy_id: string;
  label_strategy: "price_forward" | "outcome_imitation";
  label_config: LabelConfig;
  run_tag: string;
};

export type StartRunOut = {
  run_id: string;
  run_tag: string;
  git_branch: string;
  worktree_path: string;
};

export type AutoresearchRunStatus =
  | "running"
  | "completed"
  | "stopped"
  | "failed";

export type AutoresearchRunSummary = {
  run_id: string;
  run_tag: string;
  source_strategy_id: string | null;
  label_strategy: string;
  status: AutoresearchRunStatus;
  started_at: string;
  stopped_at: string | null;
  experiments: number;
  best_acc: number | null;
  best_model_id: string | null;
  // The Rust `RunSummary` returns these on BOTH the list and detail endpoints.
  git_branch: string;
  worktree_path: string;
};

// `GET /api/autoresearch/runs/:id` returns the same `RunSummary` shape as the
// list endpoint (the Rust handler returns `Json<RunSummary>`), so the detail
// type is structurally identical. Kept as an alias for call-site readability.
export type AutoresearchRunDetail = AutoresearchRunSummary;

export type AutoresearchExperimentStatus = "keep" | "discard" | "crash";

export type AutoresearchExperiment = {
  experiment_id: string;
  run_id: string;
  git_commit: string;
  val_acc: number | null;
  val_loss: number | null;
  peak_vram_mb: number | null;
  training_seconds: number | null;
  status: AutoresearchExperimentStatus;
  description: string;
  created_at: string;
};

// ─── Query key factories ───────────────────────────────────────────────────────

export const nanochatKeys = {
  all: ["nanochat"] as const,
  checkpoints: (q: { promoted_only?: boolean } = {}) =>
    [...nanochatKeys.all, "checkpoints", q] as const,
  checkpoint: (model_id: string) =>
    [...nanochatKeys.all, "checkpoints", model_id] as const,
};

export const autoresearchKeys = {
  all: ["autoresearch"] as const,
  runs: () => [...autoresearchKeys.all, "runs"] as const,
  run: (run_id: string) => [...autoresearchKeys.runs(), run_id] as const,
  experiments: (run_id: string) =>
    [...autoresearchKeys.run(run_id), "experiments"] as const,
};

// ─── Fetch functions (plain async — testable without hooks) ──────────────────

export function listNanochatCheckpoints(
  q: { promoted_only?: boolean } = {},
): Promise<NanochatCheckpoint[]> {
  const params = new URLSearchParams();
  if (q.promoted_only) params.set("promoted_only", "true");
  const qs = params.size > 0 ? `?${params.toString()}` : "";
  return apiFetch<NanochatCheckpoint[]>(`/api/nanochat/checkpoints${qs}`);
}

export function getNanochatCheckpoint(model_id: string): Promise<NanochatCheckpoint> {
  return apiFetch<NanochatCheckpoint>(
    `/api/nanochat/checkpoints/${encodeURIComponent(model_id)}`,
  );
}

export function approveNanochatCheckpoint(model_id: string): Promise<ApproveCheckpointOut> {
  return apiFetch<ApproveCheckpointOut>(
    `/api/nanochat/checkpoints/${encodeURIComponent(model_id)}/approve`,
    { method: "POST", body: JSON.stringify({}) },
  );
}

export function startAutoresearchRun(req: StartRunRequest): Promise<StartRunOut> {
  return apiFetch<StartRunOut>("/api/autoresearch/runs", {
    method: "POST",
    body: JSON.stringify(req),
  });
}

export function stopAutoresearchRun(run_id: string): Promise<unknown> {
  return apiFetch<unknown>(`/api/autoresearch/runs/${encodeURIComponent(run_id)}/stop`, {
    method: "POST",
    body: JSON.stringify({}),
  });
}

export function listAutoresearchRuns(): Promise<AutoresearchRunSummary[]> {
  return apiFetch<AutoresearchRunSummary[]>("/api/autoresearch/runs");
}

export function getAutoresearchRun(run_id: string): Promise<AutoresearchRunDetail> {
  return apiFetch<AutoresearchRunDetail>(
    `/api/autoresearch/runs/${encodeURIComponent(run_id)}`,
  );
}

export function listAutoresearchExperiments(
  run_id: string,
): Promise<AutoresearchExperiment[]> {
  return apiFetch<AutoresearchExperiment[]>(
    `/api/autoresearch/runs/${encodeURIComponent(run_id)}/experiments`,
  );
}

// ─── React Query hooks ────────────────────────────────────────────────────────

export function useNanochatCheckpoints(q: { promoted_only?: boolean } = {}) {
  return useQuery({
    queryKey: nanochatKeys.checkpoints(q),
    queryFn: () => listNanochatCheckpoints(q),
    staleTime: 30_000,
  });
}

export function useNanochatCheckpoint(model_id: string | null) {
  return useQuery({
    queryKey: nanochatKeys.checkpoint(model_id ?? ""),
    queryFn: () => getNanochatCheckpoint(model_id!),
    enabled: model_id != null,
    staleTime: 30_000,
  });
}

export function useApproveCheckpoint() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (model_id: string) => approveNanochatCheckpoint(model_id),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: nanochatKeys.all });
    },
  });
}

export function useAutoresearchRuns() {
  return useQuery({
    queryKey: autoresearchKeys.runs(),
    queryFn: listAutoresearchRuns,
    staleTime: 15_000,
    refetchInterval: 10_000,
  });
}

export function useAutoresearchRun(run_id: string | null) {
  return useQuery({
    queryKey: autoresearchKeys.run(run_id ?? ""),
    queryFn: () => getAutoresearchRun(run_id!),
    enabled: run_id != null,
    staleTime: 5_000,
    refetchInterval: (query) =>
      query.state.data?.status === "running" ? 5_000 : false,
  });
}

export function useAutoresearchExperiments(run_id: string | null) {
  return useQuery({
    queryKey: autoresearchKeys.experiments(run_id ?? ""),
    queryFn: () => listAutoresearchExperiments(run_id!),
    enabled: run_id != null,
    staleTime: 5_000,
    refetchInterval: () => {
      // Re-poll only while a run id is present (parent query drives liveness).
      return run_id ? 8_000 : false;
    },
  });
}

export function useStartRun() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: startAutoresearchRun,
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: autoresearchKeys.runs() });
    },
  });
}

export function useStopRun() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (run_id: string) => stopAutoresearchRun(run_id),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: autoresearchKeys.runs() });
    },
  });
}
