#!/usr/bin/env bash
# Point a git worktree at its OWN cargo target dir on the shared
# XvisionCargoTarget volume.
#
# WHY: all worktrees check out the same .cargo/config.toml, so they would all
# resolve build.target-dir to .../target/main. Sharing one target dir across
# trees with different sources but identical package versions makes cargo's
# mtime-based freshness check reuse stale artifacts — the symptom is ghost
# `error[E0063]: missing field ...` errors that reference code that does not
# exist in your tree (fixed in this repo 2026-08; see .cargo/config.toml).
#
# Usage: scripts/worktree-target.sh <path-to-worktree>
#        (run from anywhere; name defaults to the basename)
set -euo pipefail

wt="${1:?usage: scripts/worktree-target.sh <path-to-worktree>}"
wt="$(cd "$wt" && pwd)"
name="$(basename "$wt")"

# Compare COMMON dirs, not cwd: the main checkout and its worktrees share a
# git common dir, while two independent clones do not. The old `$(pwd)`
# comparison only worked when invoked from the main checkout root despite
# claiming "run from anywhere".
main_common="$(git -C "$wt" rev-parse --path-format=absolute --git-common-dir)"
if [ "$main_common" = "$(git -C "$wt" rev-parse --absolute-git-dir)" ]; then
  echo "refusing: $wt is the main checkout (it already owns target/main)" >&2
  exit 1
fi

mkdir -p "$wt/.cargo"
cat > "$wt/.cargo/config.toml" <<EOF
# Per-worktree cargo target dir. Generated by scripts/worktree-target.sh.
# See .cargo/config.toml in the main checkout for why sharing a target dir
# across worktrees breaks builds with ghost E0063 "missing field" errors.
[build]
target-dir = "/Volumes/XvisionCargoTarget/target/wt-$name"
EOF

echo "wrote $wt/.cargo/config.toml -> target/wt-$name"
echo "note: first build in this tree will recompile everything (cold dir)."
