import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Topbar } from "@/components/shell/Topbar";
import { Card } from "@/components/primitives/Card";
import { Pill } from "@/components/primitives/Pill";
import { ApiError } from "@/api/client";
import { listScenariosPaged, scenarioKeys } from "@/api/scenarios";
import {
  ListPagination,
  useServerPagination,
} from "@/components/primitives/ListPagination";
import type { Scenario, ScenarioSource, ListScenariosFilter } from "@/api/types.gen";

const SOURCE_TONE: Record<ScenarioSource, "default" | "gold" | "info" | "warn"> = {
  Canonical: "gold",
  User: "info",
  Clone: "default",
  Generated: "warn",
};

// Lowercase values used in the <select> option values
type SourceOption = "any" | "canonical" | "user" | "clone" | "generated";

function sourceOptionToFilter(v: SourceOption): ScenarioSource | null {
  switch (v) {
    case "canonical": return "Canonical";
    case "user": return "User";
    case "clone": return "Clone";
    case "generated": return "Generated";
    default: return null;
  }
}

function buildFilter(
  source: SourceOption,
  includeArchived: boolean,
  limit: number,
  offset: number,
): ListScenariosFilter {
  return {
    source: sourceOptionToFilter(source),
    tags: [],
    include_archived: includeArchived,
    parent_scenario_id: null,
    // `limit`/`offset` are added by the backend pagination follow-up to
    // PR #386. The ts-rs ListScenariosFilter type is regenerated by
    // cargo tests in the engine crate.
    limit,
    offset,
  };
}

export function ScenariosRoute() {
  const [source, setSource] = useState<SourceOption>("any");
  const [includeArchived, setIncludeArchived] = useState(false);

  // QA-round-7 backend-pagination follow-up (#386 gap): page-size +
  // page-nav drive `limit`/`offset` in the query key.
  const [totalFromServer, setTotalFromServer] = useState(0);
  const pager = useServerPagination(totalFromServer);
  const filter = buildFilter(source, includeArchived, pager.limit, pager.offset);

  const q = useQuery({
    queryKey: scenarioKeys.list(filter),
    queryFn: () => listScenariosPaged(filter),
    placeholderData: (prev) => prev,
  });
  useEffect(() => {
    if (q.data?.total !== undefined && q.data.total !== totalFromServer) {
      setTotalFromServer(q.data.total);
    }
  }, [q.data?.total, totalFromServer]);

  const items = q.data?.items ?? [];
  const total = q.data?.total ?? 0;

  return (
    <>
      <Topbar title="Scenarios" sub={subtitleFor(q, total)} />
      <div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <Filters
          source={source}
          onSource={setSource}
          includeArchived={includeArchived}
          onIncludeArchived={setIncludeArchived}
        />
        <Link
          to="/scenarios/new"
          className="inline-flex w-full items-center justify-center gap-1.5 rounded border border-gold px-3 py-1.5 text-[13px] font-medium text-gold transition-colors hover:bg-gold/10 sm:w-auto"
        >
          + New scenario
        </Link>
      </div>
      <Card>
        {q.isPending ? (
          <LoadingSkeleton />
        ) : q.isError ? (
          <ErrorState err={q.error} onRetry={() => q.refetch()} />
        ) : total === 0 ? (
          <EmptyState />
        ) : (
          <ScenariosTable items={items} />
        )}
      </Card>

      <ListPagination
        total={total}
        page={pager.page}
        pageSize={pager.pageSize}
        onPageChange={pager.setPage}
        onPageSizeChange={pager.setPageSize}
        itemLabel="scenarios"
      />
    </>
  );
}

function subtitleFor(
  q: { isPending: boolean; isError: boolean },
  total: number,
) {
  if (q.isPending) return "Loading…";
  if (q.isError) return "Couldn't load scenarios";
  return `${total} ${total === 1 ? "scenario" : "scenarios"}`;
}

function Filters({
  source,
  onSource,
  includeArchived,
  onIncludeArchived,
}: {
  source: SourceOption;
  onSource: (v: SourceOption) => void;
  includeArchived: boolean;
  onIncludeArchived: (v: boolean) => void;
}) {
  return (
    <div className="flex flex-wrap items-center gap-3 sm:gap-4">
      <div className="flex items-center gap-2">
        <label htmlFor="scenario-source" className="text-[12px] text-text-2">
          Source
        </label>
        <select
          id="scenario-source"
          value={source}
          onChange={(e) => onSource(e.target.value as SourceOption)}
          className="text-[12px] bg-surface-card border border-border text-text rounded px-2 py-1 outline-none focus:border-text-3"
        >
          <option value="any">(any)</option>
          <option value="canonical">Canonical</option>
          <option value="user">User</option>
          <option value="clone">Clone</option>
          <option value="generated">Generated</option>
        </select>
      </div>
      <label className="flex items-center gap-2 text-[12px] text-text-2 cursor-pointer">
        <input
          type="checkbox"
          checked={includeArchived}
          onChange={(e) => onIncludeArchived(e.target.checked)}
          className="accent-gold cursor-pointer"
        />
        Include archived
      </label>
    </div>
  );
}

function ScenariosTable({ items }: { items: Scenario[] }) {
  const navigate = useNavigate();

  function go(id: string) {
    navigate(`/scenarios/${id}`);
  }

  return (
    <>
      <div className="divide-y divide-border-soft md:hidden">
        {items.map((row) => (
          <article
            key={row.id}
            role="link"
            tabIndex={0}
            onClick={() => go(row.id)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                go(row.id);
              }
            }}
            className="px-4 py-3"
          >
            <div className="mb-1.5 flex items-start justify-between gap-2">
              <div className="text-[14px] leading-tight text-text">{row.display_name}</div>
              <SourcePill source={row.source} />
            </div>
            {row.description ? (
              <div className="mt-0.5 line-clamp-2 text-[11px] leading-tight text-text-3">
                {row.description}
              </div>
            ) : null}
            <div className="mt-1 font-mono text-[12px] text-text-2">
              {row.asset.length > 0 ? row.asset.map((a) => a.symbol).join(", ") : "—"}
              {" · "}
              {row.granularity}
            </div>
            <div className="mt-1 text-[12px] text-text-2">
              {fmtWindow(row.time_window.start, row.time_window.end)}
            </div>
            <div className="mt-2 flex flex-wrap gap-1">
              {row.tags.length > 0
                ? row.tags.slice(0, 3).map((tag) => (
                    <Pill key={tag} tone="default">
                      {tag}
                    </Pill>
                  ))
                : <span className="text-[11px] text-text-3">—</span>}
              {row.tags.length > 3 ? (
                <Pill tone="default">+{row.tags.length - 3}</Pill>
              ) : null}
            </div>
            <div className="mt-2 text-right">
              <Link
                to={`/scenarios/${row.id}`}
                className="text-[12px] text-text-3 transition-colors hover:text-text"
                tabIndex={-1}
                onClick={(e) => e.stopPropagation()}
              >
                View →
              </Link>
            </div>
          </article>
        ))}
      </div>

      <div className="hidden overflow-x-auto md:block">
        <table className="w-full">
          <thead>
            <tr className="border-b border-border-soft text-left text-[12px] text-text-2">
              <th className="py-2.5 pl-5 pr-3 font-normal">Name</th>
              <th className="px-3 py-2.5 font-normal">Asset</th>
              <th className="px-3 py-2.5 font-normal">Window</th>
              <th className="px-3 py-2.5 font-normal">Granularity</th>
              <th className="px-3 py-2.5 font-normal">Source</th>
              <th className="px-3 py-2.5 font-normal">Tags</th>
              <th className="px-5 py-2.5 text-right font-normal"></th>
            </tr>
          </thead>
          <tbody>
            {items.map((row) => (
              <tr
                key={row.id}
                role="link"
                tabIndex={0}
                onClick={() => go(row.id)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    go(row.id);
                  }
                }}
                className="cursor-pointer border-b border-border-soft transition-colors last:border-b-0 hover:bg-surface-hover focus:bg-surface-hover focus:outline-none"
              >
                <td className="py-3 pl-5 pr-3">
                  <div className="text-[13px] leading-tight text-text">{row.display_name}</div>
                  {row.description ? (
                    <div className="mt-0.5 max-w-[260px] truncate text-[11px] leading-tight text-text-3">
                      {row.description}
                    </div>
                  ) : null}
                </td>
                <td className="px-3 py-3 font-mono text-[12px] text-text-2">
                  {row.asset.length > 0 ? row.asset.map((a) => a.symbol).join(", ") : "—"}
                </td>
                <td className="whitespace-nowrap px-3 py-3 text-[12px] text-text-2">
                  {fmtWindow(row.time_window.start, row.time_window.end)}
                </td>
                <td className="px-3 py-3 font-mono text-[12px] text-text-2">
                  {row.granularity}
                </td>
                <td className="px-3 py-3">
                  <SourcePill source={row.source} />
                </td>
                <td className="px-3 py-3">
                  <div className="flex flex-wrap gap-1">
                    {row.tags.length > 0
                      ? row.tags.slice(0, 3).map((tag) => (
                          <Pill key={tag} tone="default">
                            {tag}
                          </Pill>
                        ))
                      : <span className="text-[11px] text-text-3">—</span>}
                    {row.tags.length > 3 ? (
                      <Pill tone="default">+{row.tags.length - 3}</Pill>
                    ) : null}
                  </div>
                </td>
                <td
                  className="px-5 py-3 text-right"
                  onClick={(e) => e.stopPropagation()}
                >
                  <Link
                    to={`/scenarios/${row.id}`}
                    className="text-[12px] text-text-3 transition-colors hover:text-text"
                    tabIndex={-1}
                  >
                    View →
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}

function SourcePill({ source }: { source: ScenarioSource }) {
  const tone = SOURCE_TONE[source] ?? "default";
  return <Pill tone={tone}>{source}</Pill>;
}

function fmtWindow(start: string, end: string): string {
  function fmtDate(iso: string): string {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso.slice(0, 10);
    return d.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  }
  return `${fmtDate(start)} – ${fmtDate(end)}`;
}

function LoadingSkeleton() {
  return (
    <div className="px-5 py-4 space-y-3" aria-busy>
      {Array.from({ length: 4 }).map((_, i) => (
        <div key={i} className="flex items-center gap-4 py-2">
          <div className="h-4 w-40 rounded bg-surface-elev animate-pulse" />
          <div className="h-4 w-20 rounded bg-surface-elev animate-pulse" />
          <div className="h-4 w-28 rounded bg-surface-elev animate-pulse" />
          <div className="h-4 w-16 rounded bg-surface-elev animate-pulse" />
          <div className="h-4 w-16 rounded bg-surface-elev animate-pulse" />
        </div>
      ))}
    </div>
  );
}

function EmptyState() {
  return (
    <div className="px-6 py-16 text-center text-text-2">
      <div className="font-serif italic text-[28px] text-text-3 mb-3">
        no scenarios yet
      </div>
      <p className="m-0 max-w-md mx-auto leading-snug">
        Scenarios define the market environment for eval runs. Use{" "}
        <code className="text-text font-mono">xvn scenario</code> to create
        one, or click{" "}
        <Link
          to="/scenarios/new"
          className="text-gold hover:underline underline-offset-2"
        >
          + New scenario
        </Link>{" "}
        above.
      </p>
    </div>
  );
}

function ErrorState({ err, onRetry }: { err: unknown; onRetry: () => void }) {
  const detail =
    err instanceof ApiError
      ? `${err.code}: ${err.message}`
      : err instanceof Error
        ? err.message
        : String(err);
  return (
    <div className="px-6 py-12 text-center">
      <div className="font-serif italic text-[24px] text-danger mb-3">
        couldn't load scenarios
      </div>
      <p className="m-0 mb-5 max-w-md mx-auto text-text-2 leading-snug">
        <code className="text-danger font-mono text-[12px]">{detail}</code>
      </p>
      <button
        onClick={onRetry}
        className="inline-flex items-center gap-2 px-3.5 py-2 rounded text-[13px] font-medium border border-border text-text hover:border-text-3"
      >
        Retry
      </button>
    </div>
  );
}
